(()=>{'use strict';
const client=window.getFitConnectSupabase?.(),$=s=>document.querySelector(s),status=$('#status');let rules=[],gifts=[],accounts=[],profiles=[],redemptions=[];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),slug=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),nf=new Intl.NumberFormat('nl-NL');
function msg(t,ok=false){status.textContent=t;status.style.color=ok?'#69d99a':''}function profile(id){return profiles.find(x=>x.id===id)||{full_name:'Onbekende klant',email:''}}
async function load(){if(!client){location.replace('../../login/');return}const {data:{session}}=await client.auth.getSession();if(!session){location.replace('../../login/');return}const {data:me}=await client.from('profiles').select('role').eq('id',session.user.id).single();const isDedicatedCustomer=String(session.user.email||'').toLowerCase()==='service@fit360.nl';if(me?.role!=='admin'||isDedicatedCustomer){location.replace('../../portal/?denied=admin');return}const results=await Promise.all([client.from('fitcoin_rules').select('*').order('created_at'),client.from('fitkados').select('*').order('display_order'),client.from('fitcoin_accounts').select('*').order('balance',{ascending:false}),client.from('profiles').select('id,full_name,email'),client.from('fitkado_redemptions').select('*,fitkados(name)').order('created_at',{ascending:false})]);if(results.some(x=>x.error))throw results.find(x=>x.error).error;[rules,gifts,accounts,profiles,redemptions]=results.map(x=>x.data||[]);render();msg('FitCoins-beheer is bijgewerkt.',true)}
function render(){
 $('#coinTotal').textContent=nf.format(accounts.reduce((s,x)=>s+Number(x.balance),0));$('#kadoTotal').textContent=gifts.filter(x=>x.status==='active').length;$('#requestTotal').textContent=redemptions.filter(x=>x.status==='requested').length;
 $('#ruleList').innerHTML=rules.map(x=>`<form class="card rule-editor" data-rule="${x.id}"><small>${esc(x.event_key)}</small><label>Naam<input name="name" value="${esc(x.name)}" required></label><div class="two"><label>Berekening<select name="calculationType"><option value="per_euro" ${x.calculation_type==='per_euro'?'selected':''}>FitCoins per euro</option><option value="fixed" ${x.calculation_type==='fixed'?'selected':''}>Vast aantal</option><option value="percentage" ${x.calculation_type==='percentage'?'selected':''}>Percentage</option></select></label><label>Waarde<input name="value" type="number" min="0" step="0.01" value="${x.value}" required></label></div><div class="two"><label>Minimale orderwaarde (€)<input name="minimum" type="number" min="0" step="0.01" value="${x.minimum_order_amount}"></label><label>Geldigheid (dagen)<input name="expires" type="number" min="1" value="${x.expires_after_days??''}" placeholder="Onbeperkt"></label></div><label class="check"><input name="enabled" type="checkbox" ${x.enabled?'checked':''}> Regel actief</label><button type="submit">Verdienregel opslaan</button></form>`).join('')||'<p>Nog geen verdienregels.</p>';
 $('#giftList').innerHTML=gifts.map(x=>`<article class="card gift-card">${x.image_url?`<img src="${esc(x.image_url)}" alt="${esc(x.name)}">`:''}<small>${esc(x.status)}</small><h3>${esc(x.name)}</h3><strong>${nf.format(x.coin_cost)} FitCoins</strong><p>${esc(x.description)}</p><small>Voorraad: ${x.stock==null?'onbeperkt':x.stock}</small><button data-edit-gift="${x.id}">Bewerken</button></article>`).join('')||'<p>Nog geen FitKado’s.</p>';renderAccounts();
 $('#redemptionList').innerHTML=redemptions.map(x=>{const p=profile(x.user_id);return `<div class="row"><strong>${esc(p.full_name||p.email)}</strong><span>${esc(x.fitkados?.name)}</span><span>${nf.format(x.coin_cost)} FC</span><select data-redemption="${x.id}" data-current-status="${x.status}">${['requested','approved','fulfilled','cancelled'].map(s=>`<option value="${s}" ${x.status===s?'selected':''}>${s}</option>`).join('')}</select><small>${new Date(x.created_at).toLocaleDateString('nl-NL')}</small></div>`}).join('')||'<p>Geen inwisselingen.</p>'}
function renderAccounts(){const q=$('#accountSearch').value.toLowerCase();$('#accountList').innerHTML=accounts.filter(x=>{const p=profile(x.user_id);return `${p.full_name} ${p.email}`.toLowerCase().includes(q)}).map(x=>{const p=profile(x.user_id);return `<div class="row"><div><strong>${esc(p.full_name||'Klant')}</strong><small>${esc(p.email)}</small></div><b>${nf.format(x.balance)} FC</b><span>${nf.format(x.lifetime_earned)} verdiend</span><span>${nf.format(x.lifetime_spent)} besteed</span><button data-adjust="${x.user_id}">Corrigeren</button></div>`}).join('')||'<p>Geen FitCoin-accounts gevonden.</p>'}function preview(url){const img=$('#giftImagePreview');img.hidden=!url;if(url)img.src=url}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(`#${tab.dataset.tab}`).classList.add('active')}const edit=e.target.closest('[data-edit-gift]');if(edit){const x=gifts.find(g=>g.id===edit.dataset.editGift),f=$('#giftForm');Object.entries({id:x.id,name:x.name,slug:x.slug,description:x.description,coinCost:x.coin_cost,stock:x.stock??'',imageUrl:x.image_url||'',status:x.status,displayOrder:x.display_order}).forEach(([k,v])=>f.elements[k].value=v);f.elements.featured.checked=x.featured;$('#giftTitle').textContent='FitKado bewerken';preview(x.image_url)}const adjust=e.target.closest('[data-adjust]');if(adjust){const p=profile(adjust.dataset.adjust);$('#adjustForm').elements.userId.value=adjust.dataset.adjust;$('#adjustCustomer').textContent=p.full_name||p.email;$('#adjustDialog').showModal()}});
$('#ruleList').addEventListener('submit',async e=>{e.preventDefault();const f=e.target.closest('[data-rule]');if(!f)return;const d=new FormData(f),payload={name:d.get('name').trim(),calculation_type:d.get('calculationType'),value:Number(d.get('value')),minimum_order_amount:Number(d.get('minimum')||0),expires_after_days:d.get('expires')===''?null:Number(d.get('expires')),enabled:d.get('enabled')==='on',updated_at:new Date().toISOString()};const {error}=await client.from('fitcoin_rules').update(payload).eq('id',f.dataset.rule);if(error)return msg(error.message);await load();msg('Verdienregel opgeslagen.',true)});$('#accountSearch').addEventListener('input',renderAccounts);
$('#newGift').addEventListener('click',()=>{const f=$('#giftForm');f.reset();f.elements.id.value='';f.elements.displayOrder.value=100;$('#giftTitle').textContent='Nieuw FitKado';preview('')});$('#giftForm').elements.name.addEventListener('input',e=>{if(!$('#giftForm').elements.id.value)$('#giftForm').elements.slug.value=slug(e.target.value)});$('#giftForm').elements.imageUrl.addEventListener('input',e=>preview(e.target.value));$('#giftForm').elements.imageFile.addEventListener('change',e=>preview(e.target.files[0]?URL.createObjectURL(e.target.files[0]):$('#giftForm').elements.imageUrl.value));
$('#giftForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),id=d.get('id');let imageUrl=d.get('imageUrl')||null;const file=d.get('imageFile');if(file?.size){if(file.size>5*1024*1024)return msg('De afbeelding mag maximaal 5 MB zijn.');const ext=(file.name.split('.').pop()||'webp').toLowerCase(),path=`fitkados/${crypto.randomUUID()}.${ext}`,upload=await client.storage.from('rewards-media').upload(path,file,{cacheControl:'31536000',upsert:false});if(upload.error)return msg(upload.error.message);imageUrl=client.storage.from('rewards-media').getPublicUrl(path).data.publicUrl}const payload={name:d.get('name').trim(),slug:d.get('slug').trim(),description:d.get('description').trim(),coin_cost:Number(d.get('coinCost')),stock:d.get('stock')===''?null:Number(d.get('stock')),image_url:imageUrl,status:d.get('status'),featured:d.get('featured')==='on',display_order:Number(d.get('displayOrder')||100),updated_at:new Date().toISOString()},result=id?await client.from('fitkados').update(payload).eq('id',id):await client.from('fitkados').insert(payload);if(result.error)return msg(result.error.message);f.reset();preview('');await load();msg('FitKado opgeslagen.',true)});
$('#adjustForm').addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget),{error}=await client.rpc('adjust_fitcoins',{target_user:d.get('userId'),coin_amount:Number(d.get('amount')),reason:d.get('reason')});if(error)return msg(error.message);$('#adjustDialog').close();e.currentTarget.reset();await load();msg('FitCoin-correctie verwerkt.',true)});$('#cancelAdjust').addEventListener('click',()=>$('#adjustDialog').close());
$('#redemptionList').addEventListener('change',async e=>{if(!e.target.matches('[data-redemption]'))return;const previous=e.target.dataset.currentStatus,{error}=await client.rpc('update_fitkado_redemption',{redemption_id:e.target.dataset.redemption,new_status:e.target.value});if(error){e.target.value=previous;return msg(error.message)}await load();msg('Inwisselstatus bijgewerkt.',true)});load().catch(e=>msg(e.message||'FitCoins kon niet worden geladen. Voer eerst de database-workflow uit.'));
})();
