[functions.commerce-create-payment]
verify_jwt = false

[functions.commerce-mollie-webhook]
verify_jwt = false

[functions.commerce-payment-status]
verify_jwt = false

[functions.commerce-scan-customer]
verify_jwt = true
