create table if not exists public.user_avatars (
  user_id uuid primary key references auth.users(id) on delete cascade,
  avatar_type text not null default 'standard' check (avatar_type in ('standard','ai')),
  body_type text not null default 'male' check (body_type in ('male','female','personal')),
  suit_style text not null default 'performance_black',
  status text not null default 'draft' check (status in ('draft','standard_active','uploaded','processing','ready','failed')),
  source_photo_path text,
  active_avatar_path text,
  current_version integer not null default 1 check (current_version >= 1),
  consent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.avatar_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  version integer not null check (version >= 1),
  avatar_type text not null check (avatar_type in ('standard','ai')),
  body_type text not null check (body_type in ('male','female','personal')),
  status text not null check (status in ('draft','standard_active','uploaded','processing','ready','failed')),
  source_photo_path text,
  avatar_image_path text,
  weight_kg numeric(6,2),
  bodyfat_percent numeric(5,2),
  notes text,
  created_at timestamptz not null default now(),
  unique (user_id, version)
);

alter table public.user_avatars enable row level security;
alter table public.avatar_versions enable row level security;

drop policy if exists "Users can view own avatar" on public.user_avatars;
create policy "Users can view own avatar"
on public.user_avatars for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own avatar" on public.user_avatars;
create policy "Users can create own avatar"
on public.user_avatars for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own avatar" on public.user_avatars;
create policy "Users can update own avatar"
on public.user_avatars for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can view own avatar versions" on public.avatar_versions;
create policy "Users can view own avatar versions"
on public.avatar_versions for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own avatar versions" on public.avatar_versions;
create policy "Users can create own avatar versions"
on public.avatar_versions for insert to authenticated
with check (auth.uid() = user_id);

grant select, insert, update on public.user_avatars to authenticated;
grant select, insert on public.avatar_versions to authenticated;
grant usage, select on sequence public.avatar_versions_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  false,
  10485760,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users can upload own avatar files" on storage.objects;
create policy "Users can upload own avatar files"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can view own avatar files" on storage.objects;
create policy "Users can view own avatar files"
on storage.objects for select to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can update own avatar files" on storage.objects;
create policy "Users can update own avatar files"
on storage.objects for update to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can delete own avatar files" on storage.objects;
create policy "Users can delete own avatar files"
on storage.objects for delete to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);