create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists security_events_user_created_idx
  on public.security_events(user_id, created_at desc);

alter table public.security_events enable row level security;

create policy "Users can read own security events"
  on public.security_events for select
  using (auth.uid() = user_id);

create policy "Users can insert own security events"
  on public.security_events for insert
  with check (auth.uid() = user_id);
