const fallbackProducts=[{id:'technogym-pa04',slug:'technogym-pa04',name:'Technogym PA04 verstelbare fitnessbank',category:'Kracht',description:'Professionele verstelbare fitnessbank voor dumbbell- en haltertraining.',price:1400,stock:2,delivery:'2–5 werkdagen'}];
let products=[];
const grid=document.getElementById('productGrid'),searchInput=document.getElementById('searchInput'),categoryFilter=document.getElementById('categoryFilter'),cartPanel=document.getElementById('cartPanel'),backdrop=document.getElementById('backdrop'),cartItems=document.getElementById('cartItems'),cartCount=document.getElementById('cartCount');
let cart=JSON.parse(localStorage.getItem('fitconnect-cart')||'[]');
const money=value=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(value||0));
function normalize(row){return {id:row.id||row.slug,slug:row.slug||row.id,name:row.name,category:row.category||'Overig',description:row.short_description||row.description||'',price:Number(row.price||0),stock:Number(row.stock||0),delivery:row.delivery||'Op aanvraag',images:Array.isArray(row.images)?row.images:[]}}
async function loadProducts(){try{const client=window.getFitConnectSupabase?.();if(!client){products=fallbackProducts;renderProducts();renderCart();return}const {data,error}=await client.from('products').select('id,slug,name,category,price,stock,delivery,short_description,description,images').eq('status','active').order('featured',{ascending:false}).order('name');if(error)throw error;products=(data||[]).map(normalize);if(!products.length)products=fallbackProducts}catch(error){console.error('FitConnect product load failed',error);products=fallbackProducts}renderProducts();renderCart()}
function renderProducts(){const q=searchInput.value.trim().toLowerCase(),category=categoryFilter.value,visible=products.filter(p=>(category==='Alle'||p.category===category)&&(`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q)));grid.innerHTML=visible.length?visible.map(p=>`<article class="product-card"><a class="product-visual" href="product/?slug=${encodeURIComponent(p.slug)}" aria-label="Bekijk ${p.name}"><span>${p.category.toUpperCase()}</span></a><div class="product-copy"><h3><a href="product/?slug=${encodeURIComponent(p.slug)}">${p.name}</a></h3><p>${p.description}</p><a class="detail-link" href="product/?slug=${encodeURIComponent(p.slug)}">Bekijk details en specificaties →</a><div class="product-meta"><strong>${money(p.price)} incl. btw</strong><button class="add-button" data-id="${p.id}" type="button">Toevoegen</button></div><small>${p.stock>0?`${p.stock} op voorraad`:'Leverbaar op bestelling'} · ${p.delivery}</small></div></article>`).join(''):'<div class="empty-state">Geen producten gevonden. Probeer een andere zoekterm of categorie.</div>';document.querySelectorAll('.add-button').forEach(button=>button.addEventListener('click',()=>addToCart(button.dataset.id)))}
function addToCart(id){if(!cart.includes(id))cart.push(id);saveCart();openCart()}
function removeFromCart(id){cart=cart.filter(item=>item!==id);saveCart()}
function saveCart(){localStorage.setItem('fitconnect-cart',JSON.stringify(cart));renderCart()}
function renderCart(){cartCount.textContent=cart.length;cartItems.innerHTML=cart.length?cart.map(id=>{const p=products.find(item=>String(item.id)===String(id));return p?`<div class="cart-item"><div><h4>${p.name}</h4><span>${p.category} · ${money(p.price)}</span></div><button class="remove-button" data-remove="${p.id}" type="button">Verwijder</button></div>`:''}).join(''):'<div class="empty-state">Uw winkelmand is nog leeg.</div>';document.querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>removeFromCart(button.dataset.remove)))}
function openCart(){cartPanel.classList.add('open');backdrop.classList.add('open');cartPanel.setAttribute('aria-hidden','false')}
function closeCart(){cartPanel.classList.remove('open');backdrop.classList.remove('open');cartPanel.setAttribute('aria-hidden','true')}
document.getElementById('cartButton').addEventListener('click',openCart);document.getElementById('closeCart').addEventListener('click',closeCart);backdrop.addEventListener('click',closeCart);searchInput.addEventListener('input',renderProducts);categoryFilter.addEventListener('change',renderProducts);document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{categoryFilter.value=button.dataset.category;renderProducts();document.getElementById('producten').scrollIntoView()}));document.getElementById('checkoutButton').addEventListener('click',()=>{if(!cart.length)return;const list=cart.map(id=>products.find(p=>String(p.id)===String(id))).filter(Boolean).map(p=>p.name).join('\n- '),body=encodeURIComponent(`Hallo FitConnect,\n\nIk ontvang graag prijs en advies voor:\n- ${list}\n\nNaam:\nTelefoon:\nPostcode:\nAanvullende wensen:`);window.location.href=`mailto:info@fitconnect.nl?subject=Aanvraag%20FitConnect%20Shop&body=${body}`});document.getElementById('year').textContent=new Date().getFullYear();loadProducts();