const client=window.getFitConnectSupabase?.();
const steps=[...document.querySelectorAll('.step')];
const statusEl=document.getElementById('scanStatus');
const nextButton=document.getElementById('nextButton');
const backButton=document.getElementById('backButton');
const laterButton=document.getElementById('laterButton');
let user=null,step=0,mode=null;
const draft={gender:null,birth_date:null,height_cm:null,weight_kg:null,activity_level:null,goal:null,neck_cm:null,waist_cm:null,abdomen_cm:null,hip_cm:null};
const $=id=>document.getElementById(id);
const setStatus=(text,type='error')=>{statusEl.textContent=text;statusEl.classList.toggle('success',type==='success')};
const round=(v,d=1)=>Math.round(v*10**d)/10**d;
function ageFrom(value){if(!value)return null;const b=new Date(`${value}T00:00:00`),n=new Date();let age=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))age--;return age>0?age:null}
function visibleSteps(){const list=[0,1,2,3,4,5,6];if(mode==='advanced'){list.push(7,8);if(draft.gender==='female')list.push(9)}list.push(10);return list}
function confidence(){let score=45;if(draft.gender&&draft.birth_date&&draft.height_cm&&draft.weight_kg&&draft.activity_level&&draft.goal)score=68;if(mode==='advanced'&&draft.neck_cm&&(draft.gender==='male'?draft.abdomen_cm:(draft.waist_cm&&draft.hip_cm)))score=88;return score}
function coachCopy(index){const copy={0:['Kies wat bij u past.','Snel starten is direct bruikbaar. De uitgebreide scan kunt u ook later afronden.'],1:['Identiteit voor de berekening.','Geslacht wordt gebruikt voor energie- en lichaamssamenstellingsformules.'],2:['Leeftijd verandert mee.','Uw geboortedatum maakt leeftijdsafhankelijke berekeningen automatisch actueel.'],3:['Lengte blijft uw vaste basis.','Lengte gebruiken we onder andere voor BMI en de US Navy-schatting.'],4:['Dit wordt uw nulmeting.','Gewicht is één variabele; we beoordelen het altijd samen met andere gegevens.'],5:['Uw dag telt mee.','Bureauwerk en zwaar fysiek werk leveren een heel andere energiebehoefte op.'],6:['Uw doel stuurt het plan.','Calorieën, macro’s en trainingsadvies worden hierop afgestemd.'],7:['Meet rustig en consequent.','Dezelfde meetmethode maakt toekomstige vergelijkingen betrouwbaarder.'],8:['Ontspan uw buik.','Niet inhouden of aanspannen; meet steeds op hetzelfde punt.'],9:['Meet het breedste punt.','Houd het meetlint horizontaal voor een bruikbare vergelijking.'],10:['Uw nulmeting is gereed.','Vanaf nu kan FitConnect toekomstige veranderingen tegen dit startpunt afzetten.']}[index]||['We gaan verder.','Elke stap verbetert uw persoonlijke advies.'];$('coachTitle').textContent=copy[0];$('coachText').textContent=copy[1]}
function render(){const list=visibleSteps();if(!list.includes(step))step=list.find(v=>v>step)??10;steps.forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===step));const pos=Math.max(0,list.indexOf(step));const pct=step===0?0:Math.round(pos/(list.length-1)*100);$('stepLabel').textContent=step===0?'Start':step===10?'Voltooid':`Stap ${pos} van ${list.length-2}`;$('progressPercent').textContent=`${pct}%`;$('progressBar').style.width=`${pct}%`;const conf=confidence();$('confidenceValue').textContent=`${conf}%`;$('confidenceBar').style.width=`${conf}%`;backButton.disabled=step===0;nextButton.hidden=[0,1,5,6,10].includes(step);laterButton.hidden=step===10;coachCopy(step);if(step===8){const female=draft.gender==='female';$('waistTitle').textContent=female?'Meet uw taille op het smalste punt.':'Meet uw buik op navelhoogte.';$('waistHelp').textContent=female?'Sta ontspannen en houd het meetlint horizontaal.':'Meet zonder de buik in te trekken, meestal ter hoogte van de navel.';$('waistLabel').textContent=female?'Tailleomtrek in cm':'Buikomtrek in cm'}if(step===10)showResults()}
async function saveProgress(completed=false){if(!user||!mode)return;await client.from('body_scan_progress').upsert({user_id:user.id,scan_mode:mode,current_step:step,completed,draft,updated_at:new Date().toISOString()},{onConflict:'user_id'})}
function syncInput(){if(step===2)draft.birth_date=$('birthDate').value||null;if(step===3)draft.height_cm=Number($('heightCm').value)||null;if(step===4)draft.weight_kg=Number($('weightKg').value)||null;if(step===7)draft.neck_cm=Number($('neckCm').value)||null;if(step===8){const value=Number($('waistCm').value)||null;if(draft.gender==='female')draft.waist_cm=value;else draft.abdomen_cm=value}if(step===9)draft.hip_cm=Number($('hipCm').value)||null}
function validStep(){syncInput();if(step===2)return !!draft.birth_date;if(step===3)return draft.height_cm>=100;if(step===4)return draft.weight_kg>=25;if(step===7)return draft.neck_cm>=20;if(step===8)return draft.gender==='female'?draft.waist_cm>=40:draft.abdomen_cm>=40;if(step===9)return draft.hip_cm>=50;return true}
function next(){if(!validStep()){setStatus('Vul deze stap eerst volledig in.');return}setStatus('');const list=visibleSteps(),pos=list.indexOf(step);step=list[Math.min(pos+1,list.length-1)];saveProgress();render()}
function previous(){const list=visibleSteps(),pos=list.indexOf(step);step=list[Math.max(0,pos-1)];render()}
function bodyfat(){if(mode!=='advanced'||!draft.height_cm||!draft.neck_cm)return null;const inch=v=>v/2.54,h=inch(draft.height_cm),n=inch(draft.neck_cm);let value=null;if(draft.gender==='male'&&draft.abdomen_cm){value=86.010*Math.log10(inch(draft.abdomen_cm)-n)-70.041*Math.log10(h)+36.76}else if(draft.gender==='female'&&draft.waist_cm&&draft.hip_cm){value=163.205*Math.log10(inch(draft.waist_cm)+inch(draft.hip_cm)-n)-97.684*Math.log10(h)-78.387}return Number.isFinite(value)?Math.min(70,Math.max(2,round(value,1))):null}
function showResults(){const bmi=draft.weight_kg/((draft.height_cm/100)**2),bf=bodyfat(),conf=confidence();$('resultBmi').textContent=round(bmi,1);$('resultBodyfat').textContent=bf?`${bf}%`:'Niet gemeten';$('resultMethod').textContent=bf?'US Navy-schatting':'BMI en basisgegevens';$('resultConfidence').textContent=`${conf}%`}
async function finish(){const bf=bodyfat(),bmi=round(draft.weight_kg/((draft.height_cm/100)**2),2),conf=confidence(),now=new Date().toISOString();const profile={user_id:user.id,gender:draft.gender,birth_date:draft.birth_date,height_cm:draft.height_cm,weight_kg:draft.weight_kg,activity_level:draft.activity_level,goal:draft.goal,neck_cm:draft.neck_cm,waist_cm:draft.waist_cm,abdomen_cm:draft.abdomen_cm,hip_cm:draft.hip_cm,measurement_method:bf?'navy':'quick',confidence_score:conf,scan_completed_at:now,updated_at:now};if(bf)profile.bodyfat_percent=bf;const {error}=await client.from('performance_profiles').upsert(profile,{onConflict:'user_id'});if(error){setStatus(error.message||'Opslaan is mislukt.');return}const {count}=await client.from('body_measurements').select('id',{count:'exact',head:true}).eq('user_id',user.id);await client.from('body_measurements').insert({user_id:user.id,weight_kg:draft.weight_kg,bodyfat_percent:bf,neck_cm:draft.neck_cm,waist_cm:draft.waist_cm,abdomen_cm:draft.abdomen_cm,hip_cm:draft.hip_cm,bmi,method:bf?'navy':'quick',confidence_score:conf,is_baseline:!count});await saveProgress(true);setStatus('Uw BodyScan en nulmeting zijn veilig opgeslagen.','success')}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;step=1;saveProgress();render()}));
document.querySelectorAll('.choice-grid button').forEach(b=>b.addEventListener('click',()=>{const value=b.dataset.value;if(step===1)draft.gender=value;if(step===5)draft.activity_level=value;if(step===6)draft.goal=value;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));if([1,5,6].includes(step))setTimeout(next,120)}));
nextButton.addEventListener('click',next);backButton.addEventListener('click',previous);laterButton.addEventListener('click',async()=>{syncInput();await saveProgress(false);location.href='../'});
async function init(){if(!client){location.replace('../../login/?login=required');return}const {data:{session}}=await client.auth.getSession();if(!session){location.replace('../../login/?login=required');return}user=session.user;const {data:profile}=await client.from('performance_profiles').select('*').eq('user_id',user.id).maybeSingle();if(profile)Object.keys(draft).forEach(k=>{if(profile[k]!=null)draft[k]=profile[k]});const {data:progress}=await client.from('body_scan_progress').select('*').eq('user_id',user.id).maybeSingle();if(progress&&!progress.completed){mode=progress.scan_mode;Object.assign(draft,progress.draft||{});step=progress.current_step||0;setStatus('Welkom terug. Uw eerdere voortgang is hervat.','success')}$('birthDate').value=draft.birth_date||'';$('heightCm').value=draft.height_cm||'';$('weightKg').value=draft.weight_kg||'';$('neckCm').value=draft.neck_cm||'';$('waistCm').value=draft.gender==='female'?(draft.waist_cm||''):(draft.abdomen_cm||'');$('hipCm').value=draft.hip_cm||'';render();const observer=new MutationObserver(()=>{if(step===10)finish()});observer.observe(document.querySelector('[data-step="10"]'),{attributes:true,attributeFilter:['class']})}
init().catch(e=>setStatus(e.message||'BodyScan kon niet worden geladen.'));