const client=window.getFitConnectSupabase?.();
const statusEl=document.getElementById('gymStatus');
const equipmentGrid=document.getElementById('equipmentGrid');
const exerciseGrid=document.getElementById('exerciseGrid');
let user=null,currentLocation='home',selected=new Set(),locationId=null;
const equipment=[
['chest_press','Machine chest press','Machine','Flat press met vaste bewegingsbaan'],['incline_machine','Incline chest press','Machine','Machine voor bovenborst'],['decline_machine','Decline chest press','Machine','Machine voor onderborst'],['barbell','Barbell + schijven','Vrije gewichten','Voor flat, incline en decline bench press'],['dumbbells','Dumbbells','Vrije gewichten','Voor presses en fly-varianten'],['adjustable_bench','Verstelbare bank','Banken','Flat, incline en decline posities'],['flat_bench','Flat bench','Banken','Voor flat barbell- en dumbbellpress'],['cable_machine','Cable machine','Kabel','Voor press en fly vanuit meerdere hoeken'],['pec_deck','Pec deck','Machine','Gecontroleerde fly-beweging'],['smith_machine','Smith machine','Machine','Geleide barbell press'],['dip_station','Dip station','Bodyweight','Voor borstgerichte dips'],['assisted_dip','Assisted dip','Machine','Ondersteunde dips'],['pushup_bars','Push-up bars','Budget','Meer bewegingsuitslag bij push-ups'],['resistance_bands','Resistance bands','Budget','Press en fly zonder zware apparatuur']
].map(([key,name,category,description])=>({key,name,category,description}));
const exercises=[
['Flat machine chest press','flat_press',['chest_press'],'Machine','Stabiele horizontale press voor borst, voorste schouder en triceps.'],['Flat barbell bench press','flat_press',['barbell','flat_bench'],'Barbell','Klassieke kracht- en hypertrofieoefening.'],['Flat dumbbell bench press','flat_press',['dumbbells','flat_bench'],'Dumbbells','Vrije bewegingsbaan en grote bewegingsuitslag.'],['Smith machine flat press','flat_press',['smith_machine','flat_bench'],'Smith','Geleide press met minder stabilisatievraag.'],['Cable chest press','flat_press',['cable_machine'],'Cable','Constante spanning tijdens de volledige beweging.'],['Push-up bars press','flat_press',['pushup_bars'],'Budget','Toegankelijke press met extra bewegingsuitslag.'],['Incline machine chest press','incline_press',['incline_machine'],'Machine','Gerichte press voor de bovenste borstvezels.'],['Incline barbell bench press','incline_press',['barbell','adjustable_bench'],'Barbell','Zware incline press voor kracht en massa.'],['Incline dumbbell press','incline_press',['dumbbells','adjustable_bench'],'Dumbbells','Vrije incline press met individuele armcontrole.'],['Incline Smith press','incline_press',['smith_machine','adjustable_bench'],'Smith','Geleide incline press met stabiele baan.'],['Incline cable press','incline_press',['cable_machine','adjustable_bench'],'Cable','Constante spanning vanuit een oplopende hoek.'],['Feet-elevated push-up','incline_press',['pushup_bars'],'Bodyweight','Budgetalternatief met nadruk op bovenborst.'],['Decline machine chest press','decline_press',['decline_machine'],'Machine','Press met nadruk op de onderste borstvezels.'],['Decline barbell bench press','decline_press',['barbell','adjustable_bench'],'Barbell','Zware decline press vanuit een neerwaartse bankhoek.'],['Decline dumbbell press','decline_press',['dumbbells','adjustable_bench'],'Dumbbells','Vrije decline variant met onafhankelijke armen.'],['High-to-low cable fly','fly',['cable_machine'],'Cable','Fly van hoog naar laag met nadruk op onderborst.'],['Mid cable fly','fly',['cable_machine'],'Cable','Horizontale fly met constante spanning.'],['Low-to-high cable fly','fly',['cable_machine'],'Cable','Fly van laag naar hoog voor bovenborst.'],['Pec deck fly','fly',['pec_deck'],'Machine','Gecontroleerde fly met hoge stabiliteit.'],['Dumbbell fly','fly',['dumbbells','flat_bench'],'Dumbbells','Vrije fly met nadruk op rek en controle.'],['Resistance band fly','fly',['resistance_bands'],'Budget','Compact en betaalbaar fly-alternatief.'],['Chest-focused dip','dip',['dip_station'],'Bodyweight','Voorovergebogen dip met nadruk op borst.'],['Assisted chest dip','dip',['assisted_dip'],'Machine','Ondersteunde dip voor gecontroleerde opbouw.']
].map(([name,movement,requires,type,description])=>({name,movement,requires,type,description}));
function setStatus(text,type='error'){statusEl.textContent=text;statusEl.classList.toggle('success',type==='success')}
function renderEquipment(){equipmentGrid.innerHTML=equipment.map(item=>`<button class="equipment-card ${selected.has(item.key)?'selected':''}" type="button" data-key="${item.key}"><span>${item.category}</span><strong>${item.name}</strong><small>${item.description}</small></button>`).join('');equipmentGrid.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{selected.has(b.dataset.key)?selected.delete(b.dataset.key):selected.add(b.dataset.key);renderEquipment();renderExercises()}));document.getElementById('equipmentCount').textContent=selected.size}
function renderExercises(){const filter=document.getElementById('movementFilter').value;exerciseGrid.innerHTML=exercises.filter(x=>filter==='all'||x.movement===filter).map(x=>{const available=x.requires.every(key=>selected.has(key));return `<article class="exercise-card ${available?'available':''}"><div><h3>${x.name}</h3><p>${x.description}</p><div class="tags"><span>${x.type}</span><span>${x.movement.replace('_',' ')}</span><span>${x.requires.map(key=>equipment.find(e=>e.key===key)?.name||key).join(' + ')}</span></div></div><span class="availability">${available?'Beschikbaar':'Apparatuur nodig'}</span></article>`}).join('')}
async function loadGym(){const {data:locations,error}=await client.from('training_locations').select('*').eq('user_id',user.id);if(error&&error.code!=='42P01'){setStatus(error.message);return}const found=locations?.find(x=>x.location_type===currentLocation);locationId=found?.id||null;selected.clear();if(locationId){const {data:items}=await client.from('user_equipment').select('equipment_key').eq('user_id',user.id).eq('location_id',locationId);(items||[]).forEach(x=>selected.add(x.equipment_key))}renderEquipment();renderExercises()}
async function saveGym(){if(!user)return;setStatus('Opslaan…');let id=locationId;if(!id){const names={home:'Thuisgym',commercial:'Commerciële gym',travel:'Onderweg'};const {data,error}=await client.from('training_locations').insert({user_id:user.id,name:names[currentLocation],location_type:currentLocation,is_default:currentLocation==='home'}).select('id').single();if(error){setStatus(error.message);return}id=data.id;locationId=id}await client.from('user_equipment').delete().eq('user_id',user.id).eq('location_id',id);const rows=[...selected].map(key=>{const item=equipment.find(e=>e.key===key);return {user_id:user.id,location_id:id,equipment_key:key,equipment_name:item.name,category:item.category}});if(rows.length){const {error}=await client.from('user_equipment').insert(rows);if(error){setStatus(error.message);return}}setStatus('Uw trainingslocatie en apparatuur zijn opgeslagen.','success')}
document.querySelectorAll('[data-location]').forEach(button=>button.addEventListener('click',async()=>{currentLocation=button.dataset.location;document.querySelectorAll('[data-location]').forEach(x=>x.classList.toggle('active',x===button));await loadGym()}));document.getElementById('movementFilter').addEventListener('change',renderExercises);document.getElementById('saveGym').addEventListener('click',saveGym);document.getElementById('logoutButton').addEventListener('click',async()=>{try{if(client)await client.auth.signOut({scope:'local'})}finally{location.replace('../../login/?logout=1')}});
async function init(){if(!client){location.replace('../../login/?login=required');return}const {data:{session}}=await client.auth.getSession();if(!session){location.replace('../../login/?login=required');return}user=session.user;renderEquipment();renderExercises();await loadGym()}
init().catch(e=>setStatus(e.message||'Mijn Gym kon niet worden geladen.'));