const client=window.getFitConnectSupabase?.();
const statusEl=document.getElementById('gymStatus');
const equipmentGrid=document.getElementById('equipmentGrid');
const exerciseGrid=document.getElementById('exerciseGrid');
let user=null,currentLocation='home',selected=new Set(),locationId=null;
const make=(key,name,category,description)=>({key,name,category,description});
const weighted=(prefix,label,category,weights,description)=>weights.map(weight=>make(`${prefix}_${String(weight).replace('.','_')}`,`${label} ${weight} kg`,category,description));
const sized=(prefix,label,category,sizes,unit,description)=>sizes.map(size=>make(`${prefix}_${String(size).replace('.','_')}`,`${label} ${size} ${unit}`,category,description));
const equipment=[
make('chest_press','Machine chest press','Krachtmachines','Flat press met vaste bewegingsbaan'),make('incline_machine','Incline chest press','Krachtmachines','Machine voor bovenborst'),make('decline_machine','Decline chest press','Krachtmachines','Machine voor onderborst'),make('leg_raise_machine','Leg raise machine','Krachtmachines','Ondersteunde beenheffing en coretraining'),
make('barbell','Olympische barbell + schijven','Vrije gewichten','Voor presses, squats, rows en deadlifts'),make('ez_curl_bar','EZ curlstang','Vrije gewichten','Voor curls, extensions en armtraining'),make('adjustable_dumbbells','Verstelbare dumbbells','Vrije gewichten','Compact systeem met meerdere gewichten'),...weighted('dumbbell','Dumbbell','Vrije gewichten',[1,2,3,4,5,6,8,10,12,14,16,18,20,22,5,24,26,28,30,32,36,40,45,50],'Vast gewicht voor kracht- en conditietraining'),...weighted('kettlebell','Kettlebell','Vrije gewichten',[4,6,8,10,12,14,16,20,24,28,32,36,40,44,48],'Voor swings, carries, presses en squats'),...weighted('clubbell','Clubbell','Vrije gewichten',[2,4,6,8,10,12,15,20],'Voor grip, schouders, rotatie en mobiliteit'),
make('flat_bench','Flat bench','Banken & racks','Voor flat barbell- en dumbbellpress'),make('adjustable_bench','Verstelbare bank','Banken & racks','Flat, incline en decline posities'),make('preacher_bench','Preacher bench','Banken & racks','Geïsoleerde bicep curls'),make('squat_rack','Squat rack','Banken & racks','Voor squats, presses en rack pulls'),make('power_rack','Power rack','Banken & racks','Volledig rack met safety bars'),make('half_rack','Half rack','Banken & racks','Compact rack voor barbelltraining'),
make('cable_machine','Dubbele cable machine','Kabelsystemen','Press, fly, pull en rotatie vanuit meerdere hoeken'),make('single_pulley','Single pulley / Ercolina','Kabelsystemen','Compact enkel kabelstation'),make('pec_deck','Pec deck','Krachtmachines','Gecontroleerde fly-beweging'),make('smith_machine','Smith machine','Krachtmachines','Geleide barbelltraining'),
make('dip_station','Dip station','Bodyweight','Voor dips en steunvarianten'),make('assisted_dip','Assisted dip','Krachtmachines','Ondersteunde dips en pull-ups'),make('pullup_bar','Pull-up bar','Bodyweight','Voor pull-ups, chin-ups en hanging work'),make('pushup_bars','Push-up bars','Bodyweight','Meer bewegingsuitslag bij push-ups'),make('trx','TRX / slingtrainer','Bodyweight','Suspensiontraining voor het hele lichaam'),make('ab_roller','Ab roller','Core','Uitrolbeweging voor anti-extensie'),make('weight_vest','Gewichtsvest','Bodyweight','Extra belasting bij lopen en bodyweighttraining'),
...weighted('wallball','Wallball','Ballen',[2,3,4,5,6,8,9,10,12],'Voor wall throws, squats en conditioning'),...weighted('slamball','Slamball','Ballen',[3,4,5,6,8,10,12,15,20,25,30],'Voor explosieve slams en throws'),...sized('gymball','Gymball','Ballen',[45,55,65,75,85],'cm','Voor core, mobiliteit en stabiliteit'),
...sized('plyobox','Plyobox','Plyometrie',[30,40,50,60,75,90],'cm','Voor box jumps, step-ups en plyometrie'),make('soft_plyobox','Soft plyobox verstelbaar','Plyometrie','Zachte box met meerdere hoogtes'),make('speed_ladder','Speedladder','Agility','Voor voetenwerk, snelheid en coördinatie'),make('cones','Pionnen / marker cones','Agility','Voor looplijnen, drills en veldtraining'),
make('gym_mat','Gymmat','Mobiliteit','Voor grondoefeningen, stretching en core'),make('thick_mat','Dikke fitnessmat','Mobiliteit','Extra demping voor vloertraining'),make('resistance_bands','Elastieken set','Elastieken','Lichte tot zware weerstand voor het hele lichaam'),make('mini_bands','Mini bands set','Elastieken','Voor heupen, activatie en mobiliteit'),make('power_bands','Power bands','Elastieken','Zware weerstandsbanden en pull-up assistance'),make('jump_rope','Springtouw','Conditioning','Voor conditie, ritme en voetenwerk'),make('speed_rope','Speed rope','Conditioning','Licht springtouw voor double-unders'),make('battle_ropes','Power ropes / battle ropes','Conditioning','Voor intervallen en full-body conditioning'),make('sled','Power sled','Conditioning','Voor duwen, trekken en acceleratie'),make('prowler','Prowler sled','Conditioning','Zware duw- en trekvarianten'),
make('heavy_bag','Bokszak','Boksen','Voor stoten, trappen en conditie'),make('smart_bag','Slimme bokszak','Boksen','Bokszak met sensoren en trainingsfeedback'),make('boxing_pole','Bokspaal','Boksen','Vrijstaande paal met slagvlak'),make('speed_ball','Speedball','Boksen','Voor ritme, snelheid en oog-handcoördinatie'),make('double_end_bag','Double-end bag','Boksen','Voor timing, reflexen en precisie'),...weighted('boxing_gloves','Bokshandschoenen','Boksen',[0.227,0.283,0.34,0.397,0.454],'Gewicht omgerekend vanuit 8, 10, 12, 14 en 16 oz'),
make('rower','Roeitrainer','Cardio','Full-body cardio met trekkende beweging'),make('airbike','Airbike','Cardio','Armen en benen met luchtweerstand'),make('treadmill','Loopband','Cardio','Wandelen, joggen en hardlopen'),make('curved_treadmill','Curved loopband','Cardio','Zelfaangedreven gebogen loopband'),make('cross_trainer','Crosstrainer','Cardio','Low-impact full-body cardio'),make('stair_climber','Traploper / stair climber','Cardio','Continue trapbeweging voor benen en conditie')
];
const familyMap={dumbbells:['adjustable_dumbbells',...equipment.filter(x=>x.key.startsWith('dumbbell_')).map(x=>x.key)],kettlebells:equipment.filter(x=>x.key.startsWith('kettlebell_')).map(x=>x.key),bands:['resistance_bands','mini_bands','power_bands']};
const exercises=[
['Flat machine chest press','flat_press',['chest_press'],'Machine','Stabiele horizontale press voor borst, voorste schouder en triceps.'],['Flat barbell bench press','flat_press',['barbell','flat_bench'],'Barbell','Klassieke kracht- en hypertrofieoefening.'],['Flat dumbbell bench press','flat_press',['dumbbells','flat_bench'],'Dumbbells','Vrije bewegingsbaan en grote bewegingsuitslag.'],['Smith machine flat press','flat_press',['smith_machine','flat_bench'],'Smith','Geleide press met minder stabilisatievraag.'],['Cable chest press','flat_press',['cable_machine'],'Cable','Constante spanning tijdens de volledige beweging.'],['Push-up bars press','flat_press',['pushup_bars'],'Budget','Toegankelijke press met extra bewegingsuitslag.'],['Incline machine chest press','incline_press',['incline_machine'],'Machine','Gerichte press voor de bovenste borstvezels.'],['Incline barbell bench press','incline_press',['barbell','adjustable_bench'],'Barbell','Zware incline press voor kracht en massa.'],['Incline dumbbell press','incline_press',['dumbbells','adjustable_bench'],'Dumbbells','Vrije incline press met individuele armcontrole.'],['Incline Smith press','incline_press',['smith_machine','adjustable_bench'],'Smith','Geleide incline press met stabiele baan.'],['Incline cable press','incline_press',['cable_machine','adjustable_bench'],'Cable','Constante spanning vanuit een oplopende hoek.'],['Feet-elevated push-up','incline_press',['pushup_bars'],'Bodyweight','Budgetalternatief met nadruk op bovenborst.'],['Decline machine chest press','decline_press',['decline_machine'],'Machine','Press met nadruk op de onderste borstvezels.'],['Decline barbell bench press','decline_press',['barbell','adjustable_bench'],'Barbell','Zware decline press vanuit een neerwaartse bankhoek.'],['Decline dumbbell press','decline_press',['dumbbells','adjustable_bench'],'Dumbbells','Vrije decline variant met onafhankelijke armen.'],['High-to-low cable fly','fly',['cable_machine'],'Cable','Fly van hoog naar laag met nadruk op onderborst.'],['Mid cable fly','fly',['cable_machine'],'Cable','Horizontale fly met constante spanning.'],['Low-to-high cable fly','fly',['cable_machine'],'Cable','Fly van laag naar hoog voor bovenborst.'],['Pec deck fly','fly',['pec_deck'],'Machine','Gecontroleerde fly met hoge stabiliteit.'],['Dumbbell fly','fly',['dumbbells','flat_bench'],'Dumbbells','Vrije fly met nadruk op rek en controle.'],['Resistance band fly','fly',['bands'],'Budget','Compact en betaalbaar fly-alternatief.'],['Chest-focused dip','dip',['dip_station'],'Bodyweight','Voorovergebogen dip met nadruk op borst.'],['Assisted chest dip','dip',['assisted_dip'],'Machine','Ondersteunde dip voor gecontroleerde opbouw.']
].map(([name,movement,requires,type,description])=>({name,movement,requires,type,description}));
function setStatus(text,type='error'){statusEl.textContent=text;statusEl.classList.toggle('success',type==='success')}
function hasRequirement(key){const family=familyMap[key];return family?family.some(item=>selected.has(item)):selected.has(key)}
function requirementName(key){if(key==='dumbbells')return'Dumbbells';if(key==='bands')return'Elastieken';return equipment.find(e=>e.key===key)?.name||key}
function populateCategories(){const select=document.getElementById('equipmentCategory');[...new Set(equipment.map(x=>x.category))].sort((a,b)=>a.localeCompare(b,'nl')).forEach(category=>{const option=document.createElement('option');option.value=category;option.textContent=category;select.appendChild(option)})}
function renderEquipment(){const search=document.getElementById('equipmentSearch').value.trim().toLowerCase();const category=document.getElementById('equipmentCategory').value;const visible=equipment.filter(item=>(category==='all'||item.category===category)&&(!search||`${item.name} ${item.category} ${item.description}`.toLowerCase().includes(search)));equipmentGrid.innerHTML=visible.length?visible.map(item=>`<button class="equipment-card ${selected.has(item.key)?'selected':''}" type="button" data-key="${item.key}"><span>${item.category}</span><strong>${item.name}</strong><small>${item.description}</small></button>`).join(''):'<div class="empty-equipment">Geen apparatuur gevonden met deze zoekopdracht.</div>';equipmentGrid.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{selected.has(b.dataset.key)?selected.delete(b.dataset.key):selected.add(b.dataset.key);renderEquipment();renderExercises()}));document.getElementById('equipmentCount').textContent=selected.size}
function renderExercises(){const filter=document.getElementById('movementFilter').value;exerciseGrid.innerHTML=exercises.filter(x=>filter==='all'||x.movement===filter).map(x=>{const available=x.requires.every(hasRequirement);return `<article class="exercise-card ${available?'available':''}"><div><h3>${x.name}</h3><p>${x.description}</p><div class="tags"><span>${x.type}</span><span>${x.movement.replace('_',' ')}</span><span>${x.requires.map(requirementName).join(' + ')}</span></div></div><span class="availability">${available?'Beschikbaar':'Apparatuur nodig'}</span></article>`}).join('')}
async function loadGym(){const {data:locations,error}=await client.from('training_locations').select('*').eq('user_id',user.id);if(error&&error.code!=='42P01'){setStatus(error.message);return}const found=locations?.find(x=>x.location_type===currentLocation);locationId=found?.id||null;selected.clear();if(locationId){const {data:items}=await client.from('user_equipment').select('equipment_key').eq('user_id',user.id).eq('location_id',locationId);(items||[]).forEach(x=>selected.add(x.equipment_key))}renderEquipment();renderExercises()}
async function saveGym(){if(!user)return;setStatus('Opslaan…');let id=locationId;if(!id){const names={home:'Thuisgym',commercial:'Commerciële gym',travel:'Onderweg'};const {data,error}=await client.from('training_locations').insert({user_id:user.id,name:names[currentLocation],location_type:currentLocation,is_default:currentLocation==='home'}).select('id').single();if(error){setStatus(error.message);return}id=data.id;locationId=id}await client.from('user_equipment').delete().eq('user_id',user.id).eq('location_id',id);const rows=[...selected].map(key=>{const item=equipment.find(e=>e.key===key);return {user_id:user.id,location_id:id,equipment_key:key,equipment_name:item.name,category:item.category}});if(rows.length){const {error}=await client.from('user_equipment').insert(rows);if(error){setStatus(error.message);return}}setStatus('Uw trainingslocatie en apparatuur zijn opgeslagen.','success')}
document.querySelectorAll('[data-location]').forEach(button=>button.addEventListener('click',async()=>{currentLocation=button.dataset.location;document.querySelectorAll('[data-location]').forEach(x=>x.classList.toggle('active',x===button));await loadGym()}));document.getElementById('movementFilter').addEventListener('change',renderExercises);document.getElementById('equipmentSearch').addEventListener('input',renderEquipment);document.getElementById('equipmentCategory').addEventListener('change',renderEquipment);document.getElementById('saveGym').addEventListener('click',saveGym);document.getElementById('logoutButton').addEventListener('click',async()=>{try{if(client)await client.auth.signOut({scope:'local'})}finally{location.replace('../../login/?logout=1')}});
async function init(){if(!client){location.replace('../../login/?login=required');return}const {data:{session}}=await client.auth.getSession();if(!session){location.replace('../../login/?login=required');return}user=session.user;populateCategories();renderEquipment();renderExercises();await loadGym()}
init().catch(e=>setStatus(e.message||'Mijn Gym kon niet worden geladen.'));