const client=window.getFitConnectSupabase?.();
const engine=window.FitConnectDecisionEngine;
const steps=[...document.querySelectorAll('.step')];
const statusEl=document.getElementById('intakeStatus');
const state={primary_goal:null,dream_statement:'',occupation_type:null,daily_activity:null,fitness_self_rating:null,training_experience:null,training_location:null,session_minutes:null,training_days:null,motivation_reasons:[],limitations:[],health_flags:[],confidence_barriers:[]};
let user=null,step=0;
const $=id=>document.getElementById(id);
const labels={fat_loss:'Gewicht verliezen',health:'Fitter en gezonder',condition:'Conditie verbeteren',strength:'Sterker worden',mobility:'Soepeler bewegen',vitality:'Vitaal ouder worden',boxing:'Boksen leren',selection:'Politie / Defensie'};
function setStatus(text,type='error'){statusEl.textContent=text;statusEl.classList.toggle('success',type==='success')}
function render(){steps.forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===step));$('progressBar').style.width=`${Math.round(step/8*100)}%`;$('stepLabel').textContent=step===0?'Start':step===8?'Analyse gereed':`Stap ${step} van 7`;$('backButton').disabled=step===0;$('nextButton').hidden=[0,8].includes(step);$('laterButton').hidden=step===8;const copy={0:['Eerst wil ik u leren kennen.','Iedere vraag helpt mij om een kleinere, veiligere en haalbare eerste stap te kiezen.'],1:['Uw doel geeft richting.','We beginnen bij wat u echt wilt bereiken, niet bij apparatuur of ingewikkelde schema’s.'],2:['Motivatie houdt u in beweging.','Uw persoonlijke reden helpt de coach later om passend te begeleiden.'],3:['Uw dagelijks leven telt mee.','Werk en dagelijkse beweging bepalen hoeveel belasting verstandig is.'],4:['We kijken naar vandaag.','Niet naar wat u vroeger kon, maar naar uw huidige uitgangspunt.'],5:['Veiligheid staat voorop.','Aandachtspunten leiden tot aanpassingen, alternatieven of eerst professioneel overleg.'],6:['Een drempel is geen mislukking.','Als we weten wat beginnen lastig maakt, kunnen we de eerste stap eenvoudiger maken.'],7:['Klein en haalbaar.','Tijd en locatie bepalen hoe uw eerste plan werkelijk uitvoerbaar wordt.'],8:['Uw eerste profiel is klaar.','De Decision Engine laat niet alleen zien wat wij adviseren, maar ook waarom.']}[step];$('coachTitle').textContent=copy[0];$('coachText').textContent=copy[1];if(step===8)showProfile()}
function choose(button){const wrap=button.closest('[data-field]'),field=wrap.dataset.field,value=button.dataset.value,multi=wrap.classList.contains('multi');if(multi){if(value==='none'){state[field]=['none'];wrap.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b===button))}else{state[field]=state[field].filter(x=>x!=='none');state[field].includes(value)?state[field]=state[field].filter(x=>x!==value):state[field].push(value);wrap.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',state[field].includes(b.dataset.value)))}}else{state[field]=['session_minutes','training_days'].includes(field)?Number(value):value;wrap.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b===button))}}
function validate(){if(step===1&&!state.primary_goal)return false;if(step===2&&!state.motivation_reasons.length)return false;if(step===3&&(!state.occupation_type||!state.daily_activity))return false;if(step===4&&(!state.fitness_self_rating||!state.training_experience))return false;if(step===5&&(!state.limitations.length||!state.health_flags.length))return false;if(step===6&&!state.confidence_barriers.length)return false;if(step===7&&(!state.training_location||!state.session_minutes||!state.training_days))return false;return true}
function analyse(){if(!engine)throw new Error('De FitConnect Decision Engine kon niet worden geladen.');return engine.evaluate(state)}
function listHtml(items){return items.map(item=>`<li>${item}</li>`).join('')}
function showProfile(){state.dream_statement=$('dreamStatement').value.trim();const a=analyse();$('profileName').textContent=a.performanceProfile;$('profileSummary').textContent=`Uw hoofddoel is ${labels[state.primary_goal]||'persoonlijke vooruitgang'}. ${a.summary}`;$('startLevel').textContent=a.startLevel;$('impactLevel').textContent=a.recommendedImpact;$('scheduleAdvice').textContent=`${a.recommendedDays} × ${a.recommendedMinutes} min`;$('safetyStatus').textContent=a.safetyReviewRequired?'Eerst overleg':'Geen rode vlag gemeld';$('firstStep').textContent=a.firstStep;$('trainingDirection').textContent=a.trainingDirection;$('decisionReasons').innerHTML=listHtml(a.reasons);$('performanceKit').innerHTML=listHtml(a.performanceKit);$('temporaryAvoid').innerHTML=listHtml(a.avoid)}
async function save(completed=false){if(!user)return;state.dream_statement=$('dreamStatement').value.trim();const a=analyse();const payload={user_id:user.id,...state,performance_profile:a.performanceProfile,start_level:a.startLevel,recommended_impact:a.recommendedImpact,recommended_days:a.recommendedDays,recommended_minutes:a.recommendedMinutes,safety_review_required:a.safetyReviewRequired,completed,current_step:step,draft:{...state,decision_result:a},updated_at:new Date().toISOString()};if(completed)payload.completed_at=new Date().toISOString();const {error}=await client.from('performance_intakes').upsert(payload,{onConflict:'user_id'});if(error)throw error}
function next(){if(!validate()){setStatus('Maak eerst een keuze bij alle onderdelen van deze stap.');return}setStatus('');step=Math.min(8,step+1);save(false).catch(e=>setStatus(e.message));render()}
function back(){step=Math.max(0,step-1);render()}
document.querySelectorAll('[data-field] button').forEach(b=>b.addEventListener('click',()=>choose(b)));document.querySelector('[data-start]').addEventListener('click',()=>{step=1;render()});$('nextButton').addEventListener('click',next);$('backButton').addEventListener('click',back);$('laterButton').addEventListener('click',async()=>{try{await save(false);location.href='../'}catch(e){setStatus(e.message)}});$('finishButton').addEventListener('click',async()=>{try{await save(true);setStatus('Uw Performance Intake en Decision Engine-resultaat zijn opgeslagen.','success')}catch(e){setStatus(e.message)}});$('logoutButton').addEventListener('click',async()=>{try{if(client)await client.auth.signOut({scope:'local'})}finally{location.replace('../../login/?logout=1')}});
function restoreSelections(){document.querySelectorAll('[data-field]').forEach(w=>{const f=w.dataset.field;w.querySelectorAll('button').forEach(b=>{const v=['session_minutes','training_days'].includes(f)?Number(b.dataset.value):b.dataset.value;b.classList.toggle('selected',Array.isArray(state[f])?state[f].includes(v):state[f]===v)})});$('dreamStatement').value=state.dream_statement||''}
async function init(){if(!client){location.replace('../../login/?login=required');return}const {data:{session}}=await client.auth.getSession();if(!session){location.replace('../../login/?login=required');return}user=session.user;const {data}=await client.from('performance_intakes').select('*').eq('user_id',user.id).maybeSingle();if(data){Object.keys(state).forEach(k=>{if(data[k]!=null)state[k]=data[k]});if(data.draft)Object.assign(state,data.draft);step=data.completed?8:(data.current_step||0);setStatus(data.completed?'Uw bestaande intake is geladen.':'Welkom terug. Uw intake is hervat.','success')}restoreSelections();render()}
init().catch(e=>setStatus(e.message||'Performance Intake kon niet worden geladen.'));