const client=window.getFitConnectSupabase();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let suppliers=[],customers=[],equipment=[],trainingPlans=[],serviceRequests=[],commerceOrders=[],currentImages=[];
const mediaBucket='product-media';
function money(n){return new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n||0))}
const orderLabels={processing:'Wordt verwerkt',confirmed:'Bevestigd',picking:'Wordt verzameld',packed:'Klaar voor verzending',shipped:'Verzonden',delivered:'Bezorgd',cancelled:'Geannuleerd',returned:'Retour',created:'Aangemaakt',pending:'In behandeling',paid:'Betaald',failed:'Mislukt',expired:'Verlopen',refunded:'Terugbetaald',partially_refunded:'Deels terugbetaald'};
function orderReference(order){return `FC-${order.id.slice(0,8).toUpperCase()}`}
function orderPayment(order){return [...(order.payments||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]||{status:'pending'}}
async function edgeFunctionError(error){let detail=error?.message||'Edge Function request failed',status=error?.context?.status;const response=error?.context;if(response){try{const source=typeof response.clone==='function'?response.clone():response;const body=await source.json();detail=body?.error||body?.message||detail}catch{try{const source=typeof response.clone==='function'?response.clone():response;detail=(await source.text())||detail}catch{}}}if(status&&!String(detail).includes(`HTTP ${status}`))detail=`HTTP ${status}: ${detail}`;return new Error(detail)}async function loadOrders(){const {data,error}=await client.functions.invoke('commerce-update-order',{body:{action:'list'}});if(error)throw await edgeFunctionError(error);if(data?.error)throw new Error(data.error);commerceOrders=Array.isArray(data?.orders)?data.orders:[];renderOrders();renderOrderStats()}
function renderOrderStats(){const paid=commerceOrders.filter(x=>orderPayment(x).status==='paid');$('#newOrderTotal').textContent=commerceOrders.filter(x=>['processing','confirmed'].includes(x.order_status)).length;$('#paidOrderTotal').textContent=paid.length;$('#openRevenue').textContent=money(paid.filter(x=>!['shipped','delivered','cancelled','returned'].includes(x.order_status)).reduce((sum,x)=>sum+Number(x.grand_total),0));$('#shippedOrderTotal').textContent=commerceOrders.filter(x=>['shipped','delivered'].includes(x.order_status)).length}
function renderOrders(){const query=$('#orderSearch')?.value.trim().toLowerCase()||'',filter=$('#orderStatusFilter')?.value||'all',rows=commerceOrders.filter(x=>(filter==='all'||x.order_status===filter)&&(!query||`${orderReference(x)} ${x.first_name} ${x.last_name} ${x.email}`.toLowerCase().includes(query)));$('#orderRows').innerHTML=rows.map(order=>{const payment=orderPayment(order);return `<tr><td><strong>${escapeHtml(orderReference(order))}</strong><small>${new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(order.created_at))}</small></td><td>${escapeHtml(`${order.first_name} ${order.last_name}`)}<small>${escapeHtml(order.email)}</small></td><td><strong>${escapeHtml(money(order.grand_total))}</strong></td><td><span class="status ${escapeHtml(payment.status)}">${escapeHtml(orderLabels[payment.status]||payment.status)}</span></td><td><span class="status order-${escapeHtml(order.order_status)}">${escapeHtml(orderLabels[order.order_status]||order.order_status)}</span></td><td><button type="button" data-manage-order="${order.id}">Openen</button></td></tr>`}).join('')||'<tr><td colspan="6">Geen bestellingen gevonden.</td></tr>';$$('[data-manage-order]').forEach(button=>button.addEventListener('click',()=>renderOrderDetail(button.dataset.manageOrder)))}
function renderOrderDetail(id){const order=commerceOrders.find(x=>x.id===id);if(!order)return;const address=order.shipping_address||{},payment=orderPayment(order);$('#orderAdminDetail').innerHTML=`<div class="order-detail-head"><div><p class="eyebrow">${escapeHtml(orderReference(order))}</p><h2>${escapeHtml(`${order.first_name} ${order.last_name}`)}</h2><p>${escapeHtml(order.email)} · ${escapeHtml(order.phone||'Geen telefoon')}</p></div><span class="status ${escapeHtml(payment.status)}">${escapeHtml(orderLabels[payment.status]||payment.status)}</span></div><section class="order-detail-section"><h3>Artikelen</h3>${order.items.map(item=>`<div class="order-line"><span>${escapeHtml(item.product_name)} × ${Number(item.quantity)}<small>${escapeHtml(item.sku||'')}</small></span><strong>${escapeHtml(money(Number(item.unit_price)*(1+Number(item.tax_rate)/100)*Number(item.quantity)))}</strong></div>`).join('')}<div class="order-line total"><span>Totaal incl. btw</span><strong>${escapeHtml(money(order.grand_total))}</strong></div></section><section class="order-detail-section"><h3>Bezorgadres</h3><p>${escapeHtml(`${address.street||''} ${address.house_number||''}`)}<br>${escapeHtml(`${address.postal_code||''} ${address.city||''}`)}</p></section><form id="orderManageForm" class="order-manage-form"><input type="hidden" name="orderId" value="${order.id}"><label>Orderstatus<select name="orderStatus">${['processing','confirmed','picking','packed','shipped','delivered','cancelled','returned'].map(status=>`<option value="${status}" ${order.order_status===status?'selected':''}>${escapeHtml(orderLabels[status])}</option>`).join('')}</select></label><div class="field-row"><label>Vervoerder<input name="trackingCarrier" value="${escapeHtml(order.tracking_carrier||'')}" placeholder="PostNL, DHL, eigen vervoer"></label><label>Track & Trace-code<input name="trackingCode" value="${escapeHtml(order.tracking_code||'')}"></label></div><label>Track & Trace-link<input name="trackingUrl" type="url" value="${escapeHtml(order.tracking_url||'')}" placeholder="https://"></label><p class="order-mail-note">Bij status <strong>Verzonden</strong> ontvangt de klant automatisch één verzendmail via Resend.</p><button class="primary" type="submit">Bestelling bijwerken</button></form>`;$('#orderManageForm').addEventListener('submit',saveOrder)}
async function saveOrder(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type=submit]'),fd=new FormData(form);button.disabled=true;button.textContent='Bijwerken…';try{const {data,error}=await client.functions.invoke('commerce-update-order',{body:{orderId:fd.get('orderId'),orderStatus:fd.get('orderStatus'),trackingCarrier:fd.get('trackingCarrier'),trackingCode:fd.get('trackingCode'),trackingUrl:fd.get('trackingUrl')}});if(error)throw await edgeFunctionError(error);if(data?.error)throw new Error(data.error);await loadOrders();renderOrderDetail(fd.get('orderId'));showToast(data?.emailWarning?'Bestelling bijgewerkt; verzendmail wordt opnieuw geprobeerd':data?.emailSent?'Bestelling bijgewerkt en verzendmail verstuurd':'Bestelling bijgewerkt')}catch(error){console.error(error);showToast(error.message||'Bestelling bijwerken mislukt')}finally{button.disabled=false;button.textContent='Bestelling bijwerken'}}
function showOrderLoadError(error){console.error('Orders unavailable',error);const rows=$('#orderRows');if(rows)rows.innerHTML='<tr><td colspan="6">Bestellingen konden niet worden geladen. Klik op Vernieuwen om opnieuw te proberen.</td></tr>';showToast(error?.message||'Bestellingen laden mislukt')}
function bindOrderControls(){const search=$('#orderSearch'),filter=$('#orderStatusFilter'),refresh=$('#refreshOrders');search?.addEventListener('input',renderOrders);filter?.addEventListener('change',renderOrders);refresh?.addEventListener('click',async()=>{refresh.disabled=true;refresh.textContent='Vernieuwen…';try{await loadOrders();showToast('Bestellingen bijgewerkt')}catch(error){showOrderLoadError(error)}finally{refresh.disabled=false;refresh.textContent='Vernieuwen'}})}
bindOrderControls();
(async()=>{try{const session=await requireAdmin();if(!session)return;await loadOrders();setConnection('Verbonden met FitConnect Database')}catch(error){showOrderLoadError(error);setConnection('Bestellingen konden niet worden geladen')}})();
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showToast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function slugify(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}
function openProductWorkspace(){const editor=$('#productEditor');editor.classList.add('open');editor.setAttribute('aria-hidden','false');$('#productLayout')?.classList.add('is-editing');editor.scrollTop=0}
function closeProductWorkspace(){const editor=$('#productEditor');editor.classList.remove('open');editor.setAttribute('aria-hidden','true');$('#productLayout')?.classList.remove('is-editing')}
function updateSeoPreview(){const f=$('#productForm')?.elements;if(!f)return;$('#seoPreviewTitle').textContent=f.seoTitle.value||`${f.name.value||'Producttitel'} | FitConnect`;$('#seoPreviewUrl').textContent=`fitconnect.nl/shop/product/?slug=${f.seoSlug.value||f.slug.value||''}`;$('#seoPreviewDescription').textContent=f.seoDescription.value||'De meta-description verschijnt hier.'}
function productContext(){const f=$('#productForm').elements,title=f.name.value.trim(),brand=f.brand.value.trim(),model=f.model.value.trim(),category=f.category.value,subcategory=f.subcategory.value,prompt=f.contentPrompt.value.trim();return{f,title,brand,model,category,subcategory,prompt,identity:[brand,model].filter(Boolean).join(' ')||title}}
function generateContentConcept(){const {f,title,identity,category,subcategory,prompt}=productContext();if(!title){showToast('Vul eerst de productnaam in');return}const audience=f.usageType.value||'thuisgebruik en professionele trainingsruimtes',focus=prompt||`${subcategory||category} met een betrouwbare constructie en praktische inzetbaarheid`;if(!f.shortDescription.value)f.shortDescription.value=`De ${identity} is ontwikkeld voor ${audience}, met ${focus.charAt(0).toLowerCase()+focus.slice(1)}.`;if(!f.description.value)f.description.value=`De ${identity} combineert functionele trainingsmogelijkheden met een doordachte, duurzame constructie. ${focus}.\n\nFitConnect beoordeelt samen met u of dit product past bij de beschikbare ruimte, trainingsdoelen en gewenste gebruiksintensiteit. Levering, montage, afstelling en uitleg kunnen als complete oplossing worden verzorgd.\n\nControleer vóór publicatie altijd de technische specificaties, belastbaarheid en fabrieksgegevens.`;showToast('Inhoudsconcept gemaakt — controleer de feiten voor publicatie')}
function generateSeoConcept(){const {f,title,identity,category,subcategory}=productContext();if(!title){showToast('Vul eerst de productnaam in');return}const type=subcategory||category||'fitnessapparatuur',slug=slugify([f.brand.value,f.model.value||title].filter(Boolean).join('-'));f.seoTitle.value=`${title} | FitConnect`.slice(0,60);f.seoDescription.value=`Bekijk de ${identity}: ${type.toLowerCase()} met persoonlijk advies, levering en installatie door FitConnect.`.slice(0,160);f.seoSlug.value=slug;f.slug.value=f.slug.value||slug;f.seoH1.value=title;f.seoKeywords.value=[title,f.brand.value,f.model.value,type,'fitnessapparatuur','homegym'].filter(Boolean).join(', ');f.seoProductType.value=type;f.socialTitle.value=`${title} — FitConnect`.slice(0,70);f.socialDescription.value=(f.shortDescription.value||f.seoDescription.value).slice(0,200);updateSeoPreview();showToast('Vijf SEO-lagen als concept ingevuld')}
window.fitConnectToast=showToast;
function setConnection(text){const el=$('#connectionStatus');if(el)el.textContent=text}
function openView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));
$$('[data-open]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();openView(b.dataset.open)}));
async function requireAdmin(){if(!client){location.href='login.html';return null}const {data:{session},error:sessionError}=await client.auth.getSession();if(sessionError||!session){location.href='login.html';return null}const {data:profile,error}=await client.from('profiles').select('full_name,role').eq('id',session.user.id).single();const isDedicatedCustomer=String(session.user.email||'').toLowerCase()==='service@fit360.nl';if(error||profile?.role!=='admin'||isDedicatedCustomer){location.replace('../portal/?denied=admin');return null}$('#adminName').textContent=profile.full_name||session.user.email;setConnection('Verbonden met FitConnect Database');return session}
async function loadAll(){setConnection('Gegevens synchroniseren…');const [su,c,ic,e,t,s]=await Promise.all([client.from('suppliers').select('*').order('name'),client.from('profiles').select('id,full_name,role,phone,company_name,address_line1,postal_code,city,country_code,created_at').order('created_at',{ascending:false}),client.from('invoice_customers').select('*').order('updated_at',{ascending:false}),client.from('customer_equipment').select('*,profiles(full_name),products(name)').order('created_at',{ascending:false}),client.from('training_plans').select('*').order('created_at',{ascending:false}),client.from('service_requests').select('*,profiles(full_name)').order('created_at',{ascending:false})]);const auxiliary=[su,c,ic,e,t,s];auxiliary.filter(result=>result.error).forEach(result=>console.error('Command Center module unavailable',result.error));suppliers=su.error?[]:su.data||[];customers=[...(c.error?[]:c.data||[]),...(ic.error?[]:(ic.data||[]).map(x=>({...x,full_name:x.company_name||x.contact_name,role:'invoice_customer',address_line1:x.address})))];equipment=e.error?[]:e.data||[];trainingPlans=t.error?[]:t.data||[];serviceRequests=s.error?[]:s.data||[];renderAll();try{await loadOrders()}catch(error){console.error('Orders unavailable',error);$('#orderRows').innerHTML='<tr><td colspan="6">Bestellingen konden niet worden geladen.</td></tr>'}setConnection(auxiliary.some(result=>result.error)?'Gegevens geladen · enkele modules niet beschikbaar':'Verbonden met FitConnect Database')}
function statusLabel(status){return status==='active'?'Actief':status==='archived'?'Gearchiveerd':'Concept'}
function renderStats(){const setText=(selector,value)=>{const element=$(selector);if(element)element.textContent=value};setText('#customerTotal',customers.filter(c=>c.role==='customer').length);setText('#warrantyTotal',equipment.filter(e=>!e.warranty_until||new Date(e.warranty_until)>=new Date()).length);setText('#serviceTotal',serviceRequests.filter(s=>s.status!=='closed').length)}
function syncSupplierOptions(){const selected=$('#productSupplierSelect').value,names=suppliers.filter(item=>item.status==='active').map(item=>item.name);$('#productSupplierSelect').innerHTML='<option value="">Geen leverancier</option>'+names.map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join('');if(names.includes(selected))$('#productSupplierSelect').value=selected}
function renderSuppliers(){const q=$('#supplierSearch')?.value.toLowerCase()||'',grid=$('#supplierGrid');if(!grid)return;grid.innerHTML=suppliers.filter(item=>`${item.name} ${item.contact_name||''} ${item.city||''}`.toLowerCase().includes(q)).map(item=>`<article class="brand-admin-card"><div class="brand-logo-placeholder">${escapeHtml(item.name.slice(0,2).toUpperCase())}</div><div><span class="status ${escapeHtml(item.status)}">${statusLabel(item.status)}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml([item.contact_name,item.city,item.email].filter(Boolean).join(' · '))}</p><button type="button" data-edit-supplier="${item.id}">Bewerken</button></div></article>`).join('')||'<p>Geen leveranciers gevonden.</p>';$$('[data-edit-supplier]').forEach(button=>button.addEventListener('click',()=>editSupplier(button.dataset.editSupplier)))}
function clearSupplier(){const f=$('#supplierForm');f.reset();f.elements.id.value='';f.elements.status.value='active';$('#supplierEditorTitle').textContent='Nieuwe leverancier'}
function editSupplier(id){const item=suppliers.find(row=>row.id===id);if(!item)return;openView('suppliers');const f=$('#supplierForm');Object.entries({id:item.id,name:item.name,contactName:item.contact_name||'',email:item.email||'',phone:item.phone||'',address:item.address||'',postalCode:item.postal_code||'',city:item.city||'',country:item.country||'',website:item.website||'',notes:item.notes||'',status:item.status}).forEach(([key,value])=>f.elements[key].value=value);$('#supplierEditorTitle').textContent=item.name}
function renderCustomers(){$('#customerRows').innerHTML=customers.map(c=>`<tr><td><strong>${escapeHtml(c.full_name||'Naam ontbreekt')}</strong></td><td>${escapeHtml(c.phone||'-')}</td><td>${escapeHtml(c.role)}</td></tr>`).join('')||'<tr><td colspan="3">Nog geen klanten.</td></tr>'}
function renderTraining(){$('#trainingCards').innerHTML=trainingPlans.map(t=>`<article class="panel"><span>Schema</span><h2>${escapeHtml(t.title)}</h2><p>${escapeHtml(t.description||'')}</p></article>`).join('')||'<article class="panel"><p>Nog geen trainingsschema’s.</p></article>'}
function renderWarranty(){$('#warrantyRows').innerHTML=equipment.map(e=>`<tr><td>${escapeHtml(e.profiles?.full_name||'-')}</td><td>${escapeHtml(e.products?.name||'-')}</td><td>${escapeHtml(e.purchase_date||'-')}</td><td>${escapeHtml(e.warranty_until||'-')}</td></tr>`).join('')||'<tr><td colspan="4">Nog geen registraties.</td></tr>'}
function renderService(){$('#serviceCards').innerHTML=serviceRequests.map(s=>`<article class="panel"><span class="status ${escapeHtml(s.status)}">${escapeHtml(s.status)}</span><h2>${escapeHtml(s.subject)}</h2><p>${escapeHtml(s.profiles?.full_name||'')}</p><small>${new Date(s.created_at).toLocaleDateString('nl-NL')}</small></article>`).join('')||'<article class="panel"><p>Geen open serviceverzoeken.</p></article>'}
function syncImages(){const field=$('#productImages');if(field)field.value=JSON.stringify(currentImages)}
function isWebImage(url){return /^https?:\/\//i.test(url)}
function videoEmbed(value){try{const url=new URL(value),host=url.hostname.replace(/^www\./,'').toLowerCase();let id='';if(host==='youtu.be')id=url.pathname.split('/')[1];else if(host.endsWith('youtube.com'))id=url.searchParams.get('v')||url.pathname.match(/^\/(?:embed|shorts)\/([^/?]+)/)?.[1];if(id&&/^[\w-]{6,}$/.test(id))return{provider:'YouTube',url:`https://www.youtube-nocookie.com/embed/${id}`};if(host.endsWith('vimeo.com')){id=url.pathname.match(/(?:video\/)?(\d+)/)?.[1];if(id)return{provider:'Vimeo',url:`https://player.vimeo.com/video/${id}`}}if(host.endsWith('loom.com')){id=url.pathname.match(/\/(?:share|embed)\/([\w-]+)/)?.[1];if(id)return{provider:'Loom',url:`https://www.loom.com/embed/${id}`}}if(host.endsWith('dailymotion.com')||host==='dai.ly'){id=host==='dai.ly'?url.pathname.split('/')[1]:url.pathname.match(/\/video\/([\w-]+)/)?.[1];if(id)return{provider:'Dailymotion',url:`https://www.dailymotion.com/embed/video/${id}`}}if(host.endsWith('wistia.com')||host.endsWith('wi.st')){id=url.pathname.match(/(?:medias|embed)\/([\w-]+)/)?.[1];if(id)return{provider:'Wistia',url:`https://fast.wistia.net/embed/iframe/${id}`}}return null}catch{return null}}
function renderMedia(){const grid=$('#mediaGrid');if(!grid)return;syncImages();if(!currentImages.length){grid.innerHTML='<p class="media-empty">Nog geen media toegevoegd.</p>';return}const firstPhoto=currentImages.findIndex(url=>!videoEmbed(url));grid.innerHTML=currentImages.map((url,index)=>{const video=videoEmbed(url),primary=!video&&index===firstPhoto;return`<article class="media-item ${primary?'is-primary':''}"><div class="media-preview">${video?`<div class="media-video-card"><strong>${video.provider}</strong><span>Extern gehoste productvideo</span></div>`:isWebImage(url)?`<img src="${escapeHtml(url)}" alt="Productafbeelding ${index+1}">`:'<div class="media-legacy">Bestandsnaam zonder upload</div>'}<span>${video?'Video':primary?'Hoofdfoto':`Foto ${index+1}`}</span></div><div class="media-actions"><button type="button" data-primary="${index}" ${video||primary?'disabled':''}>Hoofdfoto</button><button type="button" data-left="${index}" ${index===0?'disabled':''}>←</button><button type="button" data-right="${index}" ${index===currentImages.length-1?'disabled':''}>→</button><button type="button" data-remove-image="${index}">Verwijder</button></div></article>`}).join('');$$('[data-primary]').forEach(b=>b.addEventListener('click',()=>moveImage(Number(b.dataset.primary),0)));$$('[data-left]').forEach(b=>b.addEventListener('click',()=>moveImage(Number(b.dataset.left),Number(b.dataset.left)-1)));$$('[data-right]').forEach(b=>b.addEventListener('click',()=>moveImage(Number(b.dataset.right),Number(b.dataset.right)+1)));$$('[data-remove-image]').forEach(b=>b.addEventListener('click',()=>removeImage(Number(b.dataset.removeImage))))}
function moveImage(from,to){if(to<0||to>=currentImages.length)return;const [item]=currentImages.splice(from,1);currentImages.splice(to,0,item);renderMedia()}
function storagePathFromUrl(url){try{const marker=`/storage/v1/object/public/${mediaBucket}/`;const pos=url.indexOf(marker);return pos>=0?decodeURIComponent(url.slice(pos+marker.length)):null}catch{return null}}
async function removeImage(index){const url=currentImages[index];if(!url)return;if(!confirm('Deze afbeelding verwijderen?'))return;try{const path=storagePathFromUrl(url);if(path){const {error}=await client.storage.from(mediaBucket).remove([path]);if(error)throw error}currentImages.splice(index,1);renderMedia();showToast('Afbeelding verwijderd. Sla het product nog op.')}catch(error){showToast(error.message||'Afbeelding verwijderen mislukt')}}
function safeName(name){return name.toLowerCase().replace(/[^a-z0-9.]+/g,'-').replace(/-+/g,'-')}
async function uploadFiles(files){const valid=[...files].filter(file=>file.type.startsWith('image/'));if(!valid.length)return;const slug=$('#productForm').elements.slug.value.trim();if(!slug){showToast('Vul eerst de productslug in');return}const status=$('#uploadStatus');status.hidden=false;try{for(let i=0;i<valid.length;i++){const file=valid[i];if(file.size>10*1024*1024)throw new Error(`${file.name} is groter dan 10 MB`);status.textContent=`Uploaden ${i+1} van ${valid.length}: ${file.name}`;const path=`${slug}/${Date.now()}-${i}-${safeName(file.name)}`;const {error}=await client.storage.from(mediaBucket).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;const {data}=client.storage.from(mediaBucket).getPublicUrl(path);currentImages.push(data.publicUrl)}renderMedia();showToast('Afbeeldingen geüpload. Klik nu op Opslaan.')}catch(error){showToast(error.message||'Uploaden mislukt')}finally{status.hidden=true;$('#mediaInput').value=''}}
function clearProduct(){const f=$('#productForm');f.reset();f.elements.id.value='';f.elements.status.value='draft';f.elements.vat.value='21';f.elements.category.value='Kracht';f.elements.seoCondition.value='NewCondition';currentImages=[];renderMedia();openProductWorkspace();updateSeoPreview();$('#editorTitle').textContent='Nieuw product'}
window.addEventListener('fitconnect:product-editor-opened',event=>{const product=event.detail?.product||{};currentImages=Array.isArray(product.images)?[...product.images]:[];renderMedia();updateSeoPreview()});
$('#mediaInput').addEventListener('change',e=>uploadFiles(e.target.files));
$('#supplierForm').addEventListener('submit',async event=>{event.preventDefault();const fd=new FormData(event.currentTarget),id=fd.get('id'),payload={name:fd.get('name').trim(),contact_name:fd.get('contactName').trim()||null,email:fd.get('email').trim()||null,phone:fd.get('phone').trim()||null,address:fd.get('address').trim()||null,postal_code:fd.get('postalCode').trim()||null,city:fd.get('city').trim()||null,country:fd.get('country').trim()||null,website:fd.get('website').trim()||null,notes:fd.get('notes').trim()||null,status:fd.get('status'),updated_at:new Date().toISOString()};try{const result=id?await client.from('suppliers').update(payload).eq('id',id).select().single():await client.from('suppliers').insert(payload).select().single();if(result.error)throw result.error;const refreshed=await client.from('suppliers').select('*').order('name');if(refreshed.error)throw refreshed.error;suppliers=refreshed.data||[];syncSupplierOptions();renderSuppliers();editSupplier(result.data.id);showToast('Leverancier opgeslagen')}catch(error){showToast(error.message||'Leverancier opslaan mislukt')}});$('#newSupplier').addEventListener('click',()=>{openView('suppliers');clearSupplier()});$('#clearSupplier').addEventListener('click',clearSupplier);$('#supplierSearch').addEventListener('input',renderSuppliers);
$('#addVideoUrl').addEventListener('click',()=>{const input=$('#videoUrl'),value=input.value.trim(),video=videoEmbed(value);if(!video){showToast('Gebruik een geldige YouTube-, Vimeo-, Loom-, Wistia- of Dailymotion-link');return}if(currentImages.includes(value)){showToast('Deze video is al toegevoegd');return}currentImages.push(value);input.value='';renderMedia();showToast(`${video.provider}-video toegevoegd. Klik nu op Opslaan.`)});
const dropzone=$('#mediaDropzone');['dragenter','dragover'].forEach(name=>dropzone.addEventListener(name,e=>{e.preventDefault();dropzone.classList.add('is-dragging')}));['dragleave','drop'].forEach(name=>dropzone.addEventListener(name,e=>{e.preventDefault();dropzone.classList.remove('is-dragging')}));dropzone.addEventListener('drop',e=>uploadFiles(e.dataTransfer.files));
$('#newProduct').addEventListener('click',clearProduct);$('#closeEditor').addEventListener('click',closeProductWorkspace);$('#generateProductContent').addEventListener('click',generateContentConcept);$('#generateSeo').addEventListener('click',generateSeoConcept);['name','slug','seoTitle','seoSlug','seoDescription'].forEach(name=>$('#productForm').elements[name]?.addEventListener('input',updateSeoPreview))
$('#logoutButton').addEventListener('click',async()=>{await client.auth.signOut();location.href='login.html'});function renderAll(){renderStats();syncSupplierOptions();renderSuppliers();renderCustomers();renderTraining();renderWarranty();renderService()}
(async()=>{try{const session=await requireAdmin();if(!session)return;await loadAll()}catch(error){console.error(error);setConnection('Databaseverbinding gedeeltelijk mislukt');showToast(error.message||'Producten laden mislukt')}})();
