const seedProducts=[{id:'pa04',brand:'Technogym',model:'PA04',name:'Technogym PA04 verstelbare fitnessbank',price:1400,vat:21,stock:2,delivery:'2–5 werkdagen',warranty:'2 jaar',status:'active',shortDescription:'Professionele verstelbare fitnessbank voor dumbbell- en haltertraining.',description:'Compacte, stabiele en ergonomische trainingsbank met 7 rugstanden, 3 zitstanden, geïntegreerde wielen en transportgreep.',length:'119,8 cm',width:'69,7 cm',height:'131,2 cm',weight:'36 kg',images:'IMG_6234.JPG, IMG_6235.JPG, IMG_6236.JPG, IMG_6237.JPG, IMG_6238.JPG'},{id:'myrun',brand:'Technogym',model:'MyRun',name:'Technogym MyRun',price:3850,vat:21,stock:1,delivery:'Op afspraak',warranty:'2 jaar',status:'draft',shortDescription:'Compacte premium loopband voor thuisgebruik.',description:'Comfortabele loopband voor wandelen, hardlopen en begeleide trainingen.',length:'176 cm',width:'78,5 cm',height:'126 cm',weight:'92 kg',images:''}];
const seedCustomers=[{id:'c1',name:'Paul Roelofs',email:'paul@example.nl',project:'Premium homegym',equipment:3,portal:'Actief'},{id:'c2',name:'Naomi',email:'naomi@example.nl',project:'Compacte krachtgym',equipment:2,portal:'Uitnodigen'}];
let products=JSON.parse(localStorage.getItem('fc-admin-products')||'null')||seedProducts;let customers=JSON.parse(localStorage.getItem('fc-admin-customers')||'null')||seedCustomers;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('fc-admin-products',JSON.stringify(products));localStorage.setItem('fc-admin-customers',JSON.stringify(customers));renderAll()}
function money(n){return new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(n)}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function openView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));$$('[data-open]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();openView(b.dataset.open)}));
function renderStats(){$('#productTotal').textContent=products.filter(p=>p.status==='active').length;$('#customerTotal').textContent=customers.length;$('#warrantyTotal').textContent=customers.reduce((n,c)=>n+c.equipment,0);$('#serviceTotal').textContent='2'}
function renderRecent(){$('#recentProducts').innerHTML=products.slice(0,4).map(p=>`<div class="list-row"><div><strong>${p.name}</strong><small>${p.brand} · ${p.model}</small></div><span class="status ${p.status}">${p.status==='active'?'Actief':'Concept'}</span></div>`).join('')}
function renderProducts(){const q=$('#productSearch').value.toLowerCase(),status=$('#productStatus').value;const rows=products.filter(p=>(status==='all'||p.status===status)&&`${p.name} ${p.brand} ${p.model}`.toLowerCase().includes(q));$('#productRows').innerHTML=rows.map(p=>`<tr><td><strong>${p.name}</strong><br><small>${p.brand} · ${p.model}</small></td><td>${money(p.price)}</td><td>${p.stock}</td><td><span class="status ${p.status}">${p.status==='active'?'Actief':'Concept'}</span></td><td><button data-edit="${p.id}">Bewerken</button></td></tr>`).join('')||'<tr><td colspan="5">Geen producten gevonden.</td></tr>';$$('[data-edit]').forEach(b=>b.addEventListener('click',()=>editProduct(b.dataset.edit)))}
function renderCustomers(){$('#customerRows').innerHTML=customers.map(c=>`<tr><td><strong>${c.name}</strong><br><small>${c.email}</small></td><td>${c.project}</td><td>${c.equipment}</td><td>${c.portal}</td><td><button type="button">Open</button></td></tr>`).join('')}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;openView('products');$('#editorTitle').textContent=p.name;const f=$('#productForm');Object.keys(p).forEach(k=>{if(f.elements[k])f.elements[k].value=p[k]??''})}
function clearProduct(){const f=$('#productForm');f.reset();f.elements.id.value='';f.elements.status.value='draft';f.elements.vat.value='21';$('#editorTitle').textContent='Nieuw product'}
$('#productForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data=Object.fromEntries(fd.entries());data.price=Number(data.price);data.stock=Number(data.stock);data.vat=Number(data.vat);if(data.id){products=products.map(p=>p.id===data.id?data:p)}else{data.id=`product-${Date.now()}`;products.unshift(data)}save();editProduct(data.id);showToast('Product opgeslagen')});
$('#newProduct').addEventListener('click',clearProduct);$('#closeEditor').addEventListener('click',clearProduct);$('#duplicateProduct').addEventListener('click',()=>{const f=$('#productForm'),id=f.elements.id.value,p=products.find(x=>x.id===id);if(!p)return;const copy={...p,id:`copy-${Date.now()}`,name:`Kopie van ${p.name}`,status:'draft'};products.unshift(copy);save();editProduct(copy.id);showToast('Product gedupliceerd')});
$('#productSearch').addEventListener('input',renderProducts);$('#productStatus').addEventListener('change',renderProducts);$('#newCustomer').addEventListener('click',()=>showToast('Klantformulier volgt in de databaseversie'));
$('#resetDemo').addEventListener('click',()=>{products=structuredClone(seedProducts);customers=structuredClone(seedCustomers);save();editProduct('pa04');showToast('Demo hersteld')});
function renderAll(){renderStats();renderRecent();renderProducts();renderCustomers()}renderAll();editProduct('pa04');