const client=window.getFitConnectSupabase();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let equipment=[],trainingPlans=[],serviceRequests=[],currentImages=[];
const mediaBucket='product-media';
function money(n){return new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(n||0))}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#39;','"':'&quot;'}[c]))}
function showToast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function slugify(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}
function openProductWorkspace(){const editor=$('#productEditor');editor.classList.add('open');editor.setAttribute('aria-hidden','false');$('#productLayout')?.classList.add('is-editing');editor.scrollTop=0}
function closeProductWorkspace(){const editor=$('#productEditor');editor.classList.remove('open');editor.setAttribute('aria-hidden','true');$('#productLayout')?.classList.remove('is-editing')}
function updateSeoPreview(){const f=$('#productForm')?.elements;if(!f)return;$('#seoPreviewTitle').textContent=f.seoTitle.value||`${f.name.value||'Producttitel'} | FitConnect`;$('#seoPreviewUrl').textContent=`fitconnect.nl/shop/product/?slug=${f.seoSlug.value||f.slug.value||''}`;$('#seoPreviewDescription').textContent=f.seoDescription.value||'De meta-description verschijnt hier.'}
function productContext(){const f=$('#productForm').elements,title=f.name.value.trim(),brand=f.brand.value.trim(),model=f.model.value.trim(),category=f.category.value,subcategory=f.subcategory.value,prompt=f.contentPrompt.value.trim();return{f,title,brand,model,category,subcategory,prompt,identity:[brand,model].filter(Boolean).join(' ')||title}}
function generateContentConcept(){const {f,title,identity,category,subcategory,prompt}=productContext();if(!title){showToast('Vul eerst de productnaam in');return}const audience=f.usageType.value||'thuisgebruik en professionele trainingsruimtes',focus=prompt||`${subcategory||category} met een betrouwbare constructie en praktische inzetbaarheid`;if(!f.shortDescription.value)f.shortDescription.value=`De ${identity} is ontwikkeld voor ${audience}, met ${focus.charAt(0).toLowerCase()+focus.slice(1)}.`;if(!f.description.value)f.description.value=`De ${identity} combineert functionele trainingsmogelijkheden met een doordachte, duurzame constructie. ${focus}.

FitConnect beoordeelt samen met u of dit product past bij de beschikbare ruimte, trainingsdoelen en gewenste gebruiksintensiteit. Levering, montage, afstelling en uitleg kunnen als complete oplossing worden verzorgd.

Controleer vóór publicatie altijd de technische specificaties, belastbaarheid en fabrieksgegevens.`;showToast('Inhoudsconcept gemaakt — controleer de feiten voor publicatie')}
function generateSeoConcept(){const {f,title,identity,category,subcategory}=productContext();if(!title){showToast('Vul eerst de productnaam in');return}const type=subcategory||category||'fitnessapparatuur',slug=slugify([f.brand.value,f.model.value||title].filter(Boolean).join('-'));f.seoTitle.value=`${title} | FitConnect`.slice(0,60);f.seoDescription.value=`Bekijk de ${identity}: ${type.toLowerCase()} met persoonlijk advies, levering en installatie door FitConnect.`.slice(0,160);f.seoSlug.value=slug;f.slug.value=f.slug.value||slug;f.seoH1.value=title;f.seoKeywords.value=[title,f.brand.value,f.model.value,type,'fitnessapparatuur','homegym'].filter(Boolean).join(', ');f.seoProductType.value=type;f.socialTitle.value=`${title} — FitConnect`.slice(0,70);f.socialDescription.value=(f.shortDescription.value||f.seoDescription.value).slice(0,200);updateSeoPreview();showToast('Vijf SEO-lagen als concept ingevuld')}
window.fitConnectToast=showToast;
function setConnection(text){const el=$('#connectionStatus');if(el)el.textContent=text}
function openView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));
$$('[data-open]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();openView(b.dataset.open)}));
async function loadAll(){setConnection('Gegevens synchroniseren…');const [e,t,s]=await Promise.all([client.from('customer_equipment').select('*,profiles(full_name),products(name)').order('created_at',{ascending:false}),client.from('training_plans').select('*').order('created_at',{ascending:false}),client.from('service_requests').select('*,profiles(full_name)').order('created_at',{ascending:false})]);const auxiliary=[e,t,s];auxiliary.filter(result=>result.error).forEach(result=>console.error('Command Center module unavailable',result.error));equipment=e.error?[]:e.data||[];trainingPlans=t.error?[]:t.data||[];serviceRequests=s.error?[]:s.data||[];renderAll();setConnection(auxiliary.some(result=>result.error)?'Gegevens geladen · enkele modules niet beschikbaar':'Verbonden met FitConnect Database')}
function statusLabel(status){return status==='active'?'Actief':status==='archived'?'Gearchiveerd':'Concept'}
function renderStats(){const setText=(selector,value)=>{const element=$(selector);if(element)element.textContent=value};setText('#warrantyTotal',equipment.filter(e=>!e.warranty_until||new Date(e.warranty_until)>=new Date()).length);setText('#serviceTotal',serviceRequests.filter(s=>s.status!=='closed').length)}
function renderTraining(){$('#trainingCards').innerHTML=trainingPlans.map(t=>`<article class="panel"><span>Schema</span><h2>${escapeHtml(t.title)}</h2><p>${escapeHtml(t.description||'')}</p></article>`).join('')||'<article class="panel"><p>Nog geen trainingsschema’s.</p></article>'}
function renderWarranty(){$('#warrantyRows').innerHTML=equipment.map(e=>`<tr><td>${escapeHtml(e.profiles?.full_name||'-')}</td><td>${escapeHtml(e.products?.name||'-')}</td><td>${escapeHtml(e.purchase_date||'-')}</td><td>${escapeHtml(e.warranty_until||'-')}</td></tr>`).join('')||'<tr><td colspan="4">Nog geen registraties.</td></tr>'}
function renderService(){$('#serviceCards').innerHTML=serviceRequests.map(s=>`<article class="panel"><span class="status ${escapeHtml(s.status)}">${escapeHtml(s.status)}</span><h2>${escapeHtml(s.subject)}</h2><p>${escapeHtml(s.profiles?.full_name||'')}</p><small>${new Date(s.created_at).toLocaleDateString('nl-NL')}</small></article>`).join('')||'<article class="panel"><p>Geen open serviceverzoeken.</p></article>'}
function syncImages(){const field=$('#productImages');if(field)field.value=JSON.stringify(currentImages)}
function isWebImage(url){return /^https?:\/\//i.test(url)}
function videoEmbed(value){try{const url=new URL(value),host=url.hostname.replace(/^www\./,'').toLowerCase();let id='';if(host==='youtu.be')id=url.pathname.split('/')[1];else if(host.endsWith('youtube.com'))id=url.searchParams.get('v')||url.pathname.match(/^\/(?:embed|shorts)\/([^/?]+)/)?.[1];if(id&&/^[\w-]{6,}$/.test(id))return{provider:'YouTube',url:`https://www.youtube-nocookie.com/embed/${id}`};if(host.endsWith('vimeo.com')){id=url.pathname.match(/(?:video\/)?(\d+)/)?.[1];if(id)return{provider:'Vimeo',url:`https://player.vimeo.com/video/${id}`}}if(host.endsWith('loom.com')){id=url.pathname.match(/\/(?:share|embed)\/([\w-]+)/)?.[1];if(id)return{provider:'Loom',url:`https://www.loom.com/embed/${id}`}}if(host.endsWith('dailymotion.com')||host==='dai.ly'){id=host==='dai.ly'?url.pathname.split('/')[1]:url.pathname.match(/\/video\/([\w-]+)/)?.[1];if(id)return{provider:'Dailymotion',url:`https://www.dailymotion.com/embed/video/${id}`}}if(host.endsWith('wistia.com')||host.endsWith('wi.st')){id=url.pathname.match(/(?:medias|embed)\/([\w-]+)/)?.[1];if(id)return{provider:'Wistia',url:`https://fast.wistia.net/embed/iframe/${id}`}}return null}catch{return null}}
function renderMedia(){const grid=$('#mediaGrid');if(!grid)return;syncImages();if(!currentImages.length){grid.innerHTML='<p class="media-empty">Nog geen media toegevoegd.</p>';return}const firstPhoto=currentImages.findIndex(url=>!videoEmbed(url));grid.innerHTML=currentImages.map((url,index)=>{const video=videoEmbed(url),primary=!video&&index===firstPhoto;return`<article class="media-item ${primary?'is-primary':''}"><div class="media-preview">${video?`<div class="media-video-card"><strong>${video.provider}</strong><span>Extern gehoste productvideo</span></div>`:isWebImage(url)?`<img src="${escapeHtml(url)}" alt="Productafbeelding ${index+1}">`:'<div class="media-legacy">Bestandsnaam zonder upload</div>'}<span>${video?'Video':primary?'Hoofdfoto':`Foto ${index+1}`}</span></div><div class="media-actions"><button type="button" data-primary="${index}" ${video||primary?'disabled':''}>Hoofdfoto</button><button type="button" data-left="${index}" ${index===0?'disabled':''}>←</button><button type="button" data-right="${index}" ${index===currentImages.length-1?'disabled':''}>→</button><button type="button" data-remove-image="${index}">Verwijder</button></div></article>`}).join('');$$('[data-primary]').forEach(b=>b.addEventListener('click',()=>moveImage(Number(b.dataset.primary),0)));$$('[data-left]').forEach(b=>b.addEventListener('click',()=>moveImage(Number(b.dataset.left),Number(b.dataset.left)-1)));$$('[data-right]').forEach(b=>b.addEventListener('click',()=>moveImage(Number(b.dataset.right),Number(b.dataset.right)+1)));$$('[data-remove-image]').forEach(b=>b.addEventListener('click',()=>removeImage(Number(b.dataset.removeImage))))}
function moveImage(from,to){if(to<0||to>=currentImages.length)return;const [item]=currentImages.splice(from,1);currentImages.splice(to,0,item);renderMedia()}
function storagePathFromUrl(url){try{const marker=`/storage/v1/object/public/${mediaBucket}/`;const pos=url.indexOf(marker);return pos>=0?decodeURIComponent(url.slice(pos+marker.length)):null}catch{return null}}
async function removeImage(index){const url=currentImages[index];if(!url)return;if(!confirm('Deze afbeelding verwijderen?'))return;try{const path=storagePathFromUrl(url);if(path){const {error}=await client.storage.from(mediaBucket).remove([path]);if(error)throw error}currentImages.splice(index,1);renderMedia();showToast('Afbeelding verwijderd. Sla het product nog op.')}catch(error){showToast(error.message||'Afbeelding verwijderen mislukt')}}
function safeName(name){return name.toLowerCase().replace(/[^a-z0-9.]+/g,'-').replace(/-+/g,'-')}
async function uploadFiles(files){const valid=[...files].filter(file=>file.type.startsWith('image/'));if(!valid.length)return;const slug=$('#productForm').elements.slug.value.trim();if(!slug){showToast('Vul eerst de productslug in');return}const status=$('#uploadStatus');status.hidden=false;try{for(let i=0;i<valid.length;i++){const file=valid[i];if(file.size>10*1024*1024)throw new Error(`${file.name} is groter dan 10 MB`);status.textContent=`Uploaden ${i+1} van ${valid.length}: ${file.name}`;const path=`${slug}/${Date.now()}-${i}-${safeName(file.name)}`;const {error}=await client.storage.from(mediaBucket).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;const {data}=client.storage.from(mediaBucket).getPublicUrl(path);currentImages.push(data.publicUrl)}renderMedia();showToast('Afbeeldingen geüpload. Klik nu op Opslaan.')}catch(error){showToast(error.message||'Uploaden mislukt')}finally{status.hidden=true;$('#mediaInput').value=''}}
function clearProduct(){const f=$('#productForm');f.reset();f.elements.id.value='';f.elements.status.value='draft';f.elements.vat.value='21';f.elements.category.value='Kracht';f.elements.seoCondition.value='NewCondition';currentImages=[];renderMedia();openProductWorkspace();updateSeoPreview();$('#editorTitle').textContent='Nieuw product'}
window.addEventListener('fitconnect:product-editor-opened',event=>{const product=event.detail?.product||{};currentImages=Array.isArray(product.images)?[...product.images]:[];renderMedia();updateSeoPreview()});
$('#mediaInput').addEventListener('change',e=>uploadFiles(e.target.files));
$('#addVideoUrl').addEventListener('click',()=>{const input=$('#videoUrl'),value=input.value.trim(),video=videoEmbed(value);if(!video){showToast('Gebruik een geldige YouTube-, Vimeo-, Loom-, Wistia- of Dailymotion-link');return}if(currentImages.includes(value)){showToast('Deze video is al toegevoegd');return}currentImages.push(value);input.value='';renderMedia();showToast(`${video.provider}-video toegevoegd. Klik nu op Opslaan.`)});
const dropzone=$('#mediaDropzone');['dragenter','dragover'].forEach(name=>dropzone.addEventListener(name,e=>{e.preventDefault();dropzone.classList.add('is-dragging')}));['dragleave','drop'].forEach(name=>dropzone.addEventListener(name,e=>{e.preventDefault();dropzone.classList.remove('is-dragging')}));dropzone.addEventListener('drop',e=>uploadFiles(e.dataTransfer.files));
$('#newProduct').addEventListener('click',clearProduct);$('#closeEditor').addEventListener('click',closeProductWorkspace);$('#generateProductContent').addEventListener('click',generateContentConcept);$('#generateSeo').addEventListener('click',generateSeoConcept);['name','slug','seoTitle','seoSlug','seoDescription'].forEach(name=>$('#productForm').elements[name]?.addEventListener('input',updateSeoPreview))
function renderAll(){renderStats();renderTraining();renderWarranty();renderService()}
function startAuthorizedRuntime(){
  if(window.__fitConnectAdminRuntimeStarted)return;
  if(!document.documentElement.classList.contains('fc-admin-authorized'))return;
  window.__fitConnectAdminRuntimeStarted=true;
  setConnection('Verbonden met FitConnect Database');
  loadAll().catch(error=>{console.error(error);setConnection('Databaseverbinding gedeeltelijk mislukt');showToast(error.message||'Producten laden mislukt')});
}
if(document.documentElement.classList.contains('fc-admin-authorized')){
  startAuthorizedRuntime();
}else{
  const authObserver=new MutationObserver(()=>{
    if(!document.documentElement.classList.contains('fc-admin-authorized'))return;
    authObserver.disconnect();
    startAuthorizedRuntime();
  });
  authObserver.observe(document.documentElement,{attributes:true,attributeFilter:['class']});
}
