(()=>{
  'use strict';
  const client=window.getFitConnectSupabase?.();
  const $=selector=>document.querySelector(selector);
  const money=value=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(value||0));
  const decimal=value=>new Intl.NumberFormat('nl-NL',{minimumFractionDigits:1,maximumFractionDigits:1}).format(Number(value||0));
  const dateKey=value=>new Date(value).toLocaleDateString('en-CA',{timeZone:'Europe/Amsterdam'});
  const startOfDay=date=>new Date(date.getFullYear(),date.getMonth(),date.getDate());
  const daysAgo=days=>{const date=startOfDay(new Date());date.setDate(date.getDate()-days);return date};
  const paymentOf=order=>[...(order.payments||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]||{};
  const safe=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

  function injectBundleStyles(){if($('#bundleIntelligenceStyles'))return;const style=document.createElement('style');style.id='bundleIntelligenceStyles';style.textContent=`
  .bundle-intelligence-panel{margin:0 0 24px;padding:22px;border:1px solid #e7e7e7;border-radius:18px;background:linear-gradient(135deg,#111214,#24262a);color:#fff}.bundle-intelligence-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:18px}.bundle-intelligence-head h2{margin:3px 0 5px;font-size:22px}.bundle-intelligence-head p,.bundle-intelligence-head small{margin:0;color:#bfc2c7}.bundle-intelligence-score{min-width:92px;text-align:center;padding:12px;border-radius:14px;background:rgba(255,255,255,.08)}.bundle-intelligence-score strong{display:block;font-size:28px}.bundle-intelligence-grid{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:12px}.bundle-intelligence-grid article{padding:14px;border-radius:13px;background:rgba(255,255,255,.07)}.bundle-intelligence-grid span{display:block;color:#bfc2c7;font-size:12px}.bundle-intelligence-grid strong{display:block;margin-top:5px;font-size:18px}.bundle-health-list{display:grid;gap:9px;margin-top:16px}.bundle-health-row{display:grid;grid-template-columns:minmax(180px,1fr) 100px 110px 120px;gap:10px;align-items:center;padding:11px 13px;border-radius:11px;background:rgba(255,255,255,.06)}.bundle-health-row small{color:#bfc2c7}.bundle-health-status{font-weight:700;text-transform:capitalize}.bundle-health-status.excellent,.bundle-health-status.healthy{color:#58d68d}.bundle-health-status.attention{color:#f4d03f}.bundle-health-status.warning{color:#f5b041}.bundle-health-status.critical{color:#ff6b6b}.bundle-warning-list{margin:8px 0 0;padding-left:18px;color:#d6d8dc;font-size:12px}@media(max-width:1100px){.bundle-intelligence-grid{grid-template-columns:repeat(2,1fr)}.bundle-health-row{grid-template-columns:1fr 80px}.bundle-health-row>:nth-child(n+3){display:none}}`;
  document.head.appendChild(style)}

  async function edgeOrders(){
    const {data,error}=await client.functions.invoke('commerce-update-order',{body:{action:'list'}});
    if(error)throw error;if(data?.error)throw new Error(data.error);
    return Array.isArray(data?.orders)?data.orders:[];
  }
  async function read(table,columns='*',options={}){let query=client.from(table).select(columns);if(options.order)query=query.order(options.order,{ascending:false});const {data,error}=await query;if(error)throw error;return data||[]}
  async function readBundleSummary(){const {data,error}=await client.rpc('commerce_bundle_intelligence_summary');if(error)throw error;return Array.isArray(data)?data[0]||{}:data||{}}
  function priority(type,title,detail,action,view){return{type,title,detail,action,view}}
  function buildPriorities(state){
    const items=[],unpaid=state.orders.filter(order=>['failed','expired'].includes(paymentOf(order).status)),fulfilment=state.orders.filter(order=>paymentOf(order).status==='paid'&&!['shipped','delivered','cancelled','returned'].includes(order.order_status)),lowStock=state.products.filter(product=>product.status==='active'&&Number(product.stock||0)<=2),openService=state.service.filter(item=>item.status!=='closed'),criticalBundles=state.bundleIntelligence.filter(item=>item.health_status==='critical'),warningBundles=state.bundleIntelligence.filter(item=>['attention','warning'].includes(item.health_status));
    if(criticalBundles.length)items.push(priority('high',`${criticalBundles.length} kritieke ${criticalBundles.length===1?'combinatiedeal':'combinatiedeals'}`,criticalBundles.slice(0,3).map(item=>item.name).join(', ')+(criticalBundles.length>3?' en meer.':'.'),'Deals analyseren','combination-deals'));
    if(fulfilment.length)items.push(priority('high',`${fulfilment.length} betaalde ${fulfilment.length===1?'bestelling wacht':'bestellingen wachten'} op verwerking`,`${money(fulfilment.reduce((sum,item)=>sum+Number(item.grand_total||0),0))} moet nog worden verzameld of verzonden.`,'Orders openen','orders'));
    if(openService.length)items.push(priority(openService.length>3?'high':'medium',`${openService.length} open service${openService.length===1?'verzoek':'verzoeken'}`,'Controleer responstijd, eigenaar en eerstvolgende actie.','Service openen','service'));
    if(lowStock.length)items.push(priority('medium',`${lowStock.length} actieve ${lowStock.length===1?'voorraadpositie is':'voorraadposities zijn'} laag`,lowStock.slice(0,3).map(item=>item.name).join(', ')+(lowStock.length>3?' en meer.':'.'),'Voorraad bekijken','products'));
    if(warningBundles.length)items.push(priority('medium',`${warningBundles.length} ${warningBundles.length===1?'bundel vraagt':'bundels vragen'} aandacht`,'Controleer marge, korting en leverbare capaciteit.','Bundle Intelligence','combination-deals'));
    if(unpaid.length)items.push(priority('medium',`${unpaid.length} mislukte of verlopen ${unpaid.length===1?'betaling':'betalingen'}`,'Beoordeel of opvolging of checkout-analyse nodig is.','Betalingen bekijken','orders'));
    if(!items.length)items.push(priority('good','Geen kritieke operationele blokkades','Orders, service, voorraad en combinatiedeals bevinden zich binnen de ingestelde grenzen.','Dashboard actueel','dashboard'));
    return items;
  }
  function renderPriorities(items){$('#priorityCount').textContent=`${items.length} ${items.length===1?'signaal':'signalen'}`;$('#priorityFeed').innerHTML=items.map(item=>`<article class="priority-item ${safe(item.type)}"><i></i><div><strong>${safe(item.title)}</strong><span>${safe(item.detail)}</span></div><button type="button" data-intelligence-open="${safe(item.view)}">${safe(item.action)}</button></article>`).join('');document.querySelectorAll('[data-intelligence-open]').forEach(button=>button.addEventListener('click',()=>document.querySelector(`[data-view="${button.dataset.intelligenceOpen}"]`)?.click()))}
  function renderChart(orders){const days=Array.from({length:7},(_,index)=>{const date=daysAgo(6-index);return{date,key:dateKey(date),total:0}});orders.filter(order=>paymentOf(order).status==='paid').forEach(order=>{const key=dateKey(paymentOf(order).paid_at||order.completed_at||order.created_at),day=days.find(item=>item.key===key);if(day)day.total+=Number(order.grand_total||0)});const max=Math.max(...days.map(day=>day.total),1);$('#revenueChart').innerHTML=days.map(day=>`<div class="chart-day" title="${safe(money(day.total))}"><i style="height:${Math.max(3,(day.total/max)*100)}%"></i><strong>${safe(money(day.total))}</strong><span>${day.date.toLocaleDateString('nl-NL',{weekday:'short'})}</span></div>`).join('')}
  function renderHealth(state,priorities){const activeProducts=state.products.filter(item=>item.status==='active'),bundleScore=Number(state.bundleSummary.average_health_score||100),dimensions=[['Commerce',Math.max(0,100-priorities.filter(item=>item.type==='high').length*25)],['Voorraad',activeProducts.length?Math.round(activeProducts.filter(item=>Number(item.stock||0)>2).length/activeProducts.length*100):100],['Bundle Engine',Math.round(bundleScore)],['Service',Math.max(0,100-state.service.filter(item=>item.status!=='closed').length*10)],['Datakwaliteit',activeProducts.length?Math.round(activeProducts.filter(item=>item.name&&item.price!=null&&item.brand).length/activeProducts.length*100):100]];const score=Math.round(dimensions.reduce((sum,item)=>sum+item[1],0)/dimensions.length);$('#healthScore').textContent=`${score}/100`;$('#healthGauge').style.width=`${score}%`;$('#healthDimensions').innerHTML=dimensions.map(([label,value])=>`<div class="health-row"><span>${safe(label)}</span><b>${value}%</b><div><i style="width:${value}%"></i></div></div>`).join('')}
  function renderChecks(state){const active=state.products.filter(item=>item.status==='active'),missingMedia=active.filter(item=>!Array.isArray(item.images)||!item.images.length).length,missingCosts=active.filter(item=>Number(item.purchase_price||0)<=0).length,checks=[['Databaseverbinding','Verbonden','ok'],['Commerce orderstroom',`${state.orders.length} orders bereikbaar`,'ok'],['Bundle Intelligence',`${state.bundleIntelligence.length} deals berekend`,'ok'],['Inkoopprijzen',missingCosts?`${missingCosts} actief zonder inkoopprijs`:'Compleet',missingCosts?'warning':'ok'],['Productmedia',missingMedia?`${missingMedia} actief zonder foto`:'Compleet',missingMedia?'warning':'ok'],['Klantprofielen',`${state.customers.length} profielen bereikbaar`,'ok'],['Laatste synchronisatie',new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}),'ok']];$('#systemChecks').innerHTML=checks.map(([label,value,status])=>`<div class="system-check ${status}"><i></i><span>${safe(label)}</span><small>${safe(value)}</small></div>`).join('')}
  function renderKpis(state,priorities){const cutoff=daysAgo(30),previousCutoff=daysAgo(60),paid=state.orders.filter(order=>paymentOf(order).status==='paid'),current=paid.filter(order=>new Date(paymentOf(order).paid_at||order.created_at)>=cutoff),previous=paid.filter(order=>{const date=new Date(paymentOf(order).paid_at||order.created_at);return date>=previousCutoff&&date<cutoff}),revenue=current.reduce((sum,item)=>sum+Number(item.grand_total||0),0),previousRevenue=previous.reduce((sum,item)=>sum+Number(item.grand_total||0),0),delta=previousRevenue?Math.round((revenue-previousRevenue)/previousRevenue*100):null,customers=state.customers.filter(item=>item.role==='customer'),newCustomers=customers.filter(item=>new Date(item.created_at)>=cutoff).length,pressure=priorities.filter(item=>item.type!=='good').length;$('#executiveRevenue').textContent=money(revenue);$('#revenueDelta').textContent=delta===null?'Nog geen vergelijkingsperiode':`${delta>=0?'+':''}${delta}% versus vorige periode`;$('#executivePaidOrders').textContent=String(current.length);$('#averageOrderValue').textContent=`${money(current.length?revenue/current.length:0)} gemiddeld`;$('#executiveCustomers').textContent=String(customers.length);$('#newCustomersLabel').textContent=`${newCustomers} nieuw in 30 dagen`;$('#executivePressure').textContent=String(pressure);$('#pressureLabel').textContent=pressure?`${priorities.filter(item=>item.type==='high').length} hoge prioriteit`:'Alles onder controle';const activeProducts=state.products.filter(item=>item.status==='active');$('#intelligenceProductCount').textContent=String(activeProducts.length);$('#intelligenceStockCount').textContent=String(activeProducts.reduce((sum,item)=>sum+Number(item.stock||0),0))}
  function warningText(warnings){const rows=Array.isArray(warnings)?warnings:[];return rows.length?`<ul class="bundle-warning-list">${rows.slice(0,3).map(item=>`<li>${safe(item.message||item.code)}</li>`).join('')}</ul>`:''}
  function renderBundleIntelligence(state){injectBundleStyles();const view=$('#combination-deals');if(!view)return;let panel=$('#bundleIntelligencePanel');if(!panel){panel=document.createElement('section');panel.id='bundleIntelligencePanel';panel.className='bundle-intelligence-panel';const anchor=view.querySelector('.bundle-workspace')||view.firstElementChild;anchor?.before(panel)}const summary=state.bundleSummary||{},rows=[...state.bundleIntelligence].sort((a,b)=>Number(a.health_score||0)-Number(b.health_score||0));panel.innerHTML=`<div class="bundle-intelligence-head"><div><small>Commerce Intelligence Engine</small><h2>Bundle Intelligence</h2><p>Live marge-, voorraad- en gezondheidsanalyse van alle combinatiedeals.</p></div><div class="bundle-intelligence-score"><span>Gemiddeld</span><strong>${decimal(summary.average_health_score)}/100</strong></div></div><div class="bundle-intelligence-grid"><article><span>Actieve deals</span><strong>${Number(summary.active_bundles||0)}</strong></article><article><span>Gezonde deals</span><strong>${Number(summary.healthy_bundles||0)}</strong></article><article><span>Kritiek</span><strong>${Number(summary.critical_bundles||0)}</strong></article><article><span>Potentiële omzet</span><strong>${money(summary.potential_revenue)}</strong></article><article><span>Winstpotentie</span><strong>${money(summary.potential_gross_margin)}</strong></article></div><div class="bundle-health-list">${rows.slice(0,10).map(item=>`<article class="bundle-health-row"><div><strong>${safe(item.name)}</strong><small>${safe(item.category||item.brand||item.slug||'Combinatiedeal')}</small>${warningText(item.warnings)}</div><span class="bundle-health-status ${safe(item.health_status||'critical')}">${safe(item.health_status||'critical')}</span><span>${decimal(item.gross_margin_percent)}% marge</span><span>${Number(item.stock_capacity||0)} leverbaar</span></article>`).join('')||'<p>Nog geen Bundle Intelligence-data beschikbaar.</p>'}</div>`}
  async function load(){const button=$('#refreshIntelligence');if(!client)return;if(button){button.disabled=true;button.textContent='Analyseren…'}try{const results=await Promise.allSettled([edgeOrders(),read('products'),read('profiles','id,full_name,role,created_at'),read('service_requests'),read('commerce_bundle_intelligence','*',{order:'health_score'}),readBundleSummary()]);const required=[results[0],results[1],results[2]];if(required.some(result=>result.status==='rejected'))throw new Error('Een verplichte databron is niet bereikbaar');const state={orders:results[0].value,products:results[1].value,customers:results[2].value,service:results[3].status==='fulfilled'?results[3].value:[],bundleIntelligence:results[4].status==='fulfilled'?results[4].value:[],bundleSummary:results[5].status==='fulfilled'?results[5].value:{}};const priorities=buildPriorities(state);renderKpis(state,priorities);renderPriorities(priorities);renderHealth(state,priorities);renderChart(state.orders);renderChecks(state);renderBundleIntelligence(state);$('#intelligenceTimestamp').textContent=`Live bijgewerkt op ${new Date().toLocaleString('nl-NL',{dateStyle:'long',timeStyle:'short'})}`}catch(error){console.error('Command Center Intelligence',error);$('#priorityFeed').innerHTML=`<article class="priority-item high"><i></i><div><strong>Bedrijfsbeeld kon niet volledig worden opgebouwd</strong><span>${safe(error.message||'Onbekende synchronisatiefout')}</span></div></article>`;window.fitConnectToast?.('Executive Intelligence kon niet volledig laden')}finally{if(button){button.disabled=false;button.textContent='Alles vernieuwen'}}}
  $('#refreshIntelligence')?.addEventListener('click',load);document.querySelector('[data-view="combination-deals"]')?.addEventListener('click',()=>setTimeout(load,150));window.addEventListener('load',()=>setTimeout(load,250));
})();