(()=>{
  const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
  const client=window.getFitConnectSupabase?.();
  const defaults={headingSize:36,accent:'#f36f21',density:'comfortable',drawerSide:'right',contentWidth:1920,radius:18,appearance:'light'};
  function readLocal(){try{return {...defaults,...JSON.parse(localStorage.getItem('fitconnect-os-interface')||'{}')}}catch{return {...defaults}}}
  let settings=readLocal();
  function addTypographyLink(){const nav=document.querySelector('.sidebar nav');if(!nav||document.getElementById('typographyControlLink')||nav.querySelector('a[href="typography/"]'))return;const link=document.createElement('a');link.id='typographyControlLink';link.className='nav-item module-live';link.href='typography/';link.innerHTML='Typografie <span>Control</span>';nav.appendChild(link)}
  function ensureCombinationDealsNavigation(){const button=document.querySelector('[data-view="combination-deals"]');if(!button)return;button.hidden=false;button.removeAttribute('hidden');button.style.removeProperty('display');button.style.removeProperty('visibility');button.setAttribute('aria-disabled','false')}
  function injectAppearanceSetting(){const body=$('#settingsDrawer .settings-body');if(!body||$('#appearanceSelect'))return;const section=document.createElement('div');section.className='settings-section';section.innerHTML='<label class="setting-label" for="appearanceSelect">Kleurmodus</label><select id="appearanceSelect"><option value="light">Licht</option><option value="dark">Donker</option><option value="system">Systeeminstelling</option></select><small style="color:var(--muted)">Past het volledige Command Center aan zonder de website-theme te wijzigen.</small>';body.prepend(section);section.querySelector('select').addEventListener('change',event=>{settings.appearance=event.target.value;apply()})}
  function resolvedAppearance(){return settings.appearance==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):settings.appearance}
  function apply(){document.documentElement.style.setProperty('--heading-size',`${settings.headingSize}px`);document.documentElement.style.setProperty('--accent',settings.accent);document.documentElement.style.setProperty('--content-width',`${settings.contentWidth}px`);document.body.classList.toggle('density-compact',settings.density==='compact');document.body.classList.toggle('theme-dark',resolvedAppearance()==='dark');const drawer=$('#settingsDrawer');if(drawer)drawer.classList.toggle('left',settings.drawerSide==='left');if($('#appearanceSelect'))$('#appearanceSelect').value=settings.appearance;if($('#headingSize'))$('#headingSize').value=settings.headingSize;if($('#headingSizeValue'))$('#headingSizeValue').textContent=`${settings.headingSize} px`;if($('#customAccent'))$('#customAccent').value=settings.accent;if($('#densitySelect'))$('#densitySelect').value=settings.density;if($('#drawerSide'))$('#drawerSide').value=settings.drawerSide;if($('#contentWidth')){$('#contentWidth').max='1920';$('#contentWidth').value=settings.contentWidth}if($('#contentWidthValue'))$('#contentWidthValue').textContent=settings.contentWidth>=1880?'Volledige ruimte':`${settings.contentWidth} px`;$$('#colorOptions button').forEach(button=>button.classList.toggle('active',button.dataset.color?.toLowerCase()===settings.accent.toLowerCase()))}
  async function loadPublishedTheme(){if(!client)return;const {data,error}=await client.from('site_theme_settings').select('*').eq('id','default').single();if(error){console.warn(error.message);return}settings={...settings,accent:data.accent,headingSize:data.heading_size,contentWidth:Math.max(Number(data.content_width||0),settings.contentWidth),density:data.density,radius:data.radius||18};apply()}
  function open(){apply();$('#settingsDrawer')?.classList.add('open');$('#drawerBackdrop')?.classList.add('open');$('#settingsDrawer')?.setAttribute('aria-hidden','false');$('#settingsButton')?.setAttribute('aria-expanded','true')}
  function close(){$('#settingsDrawer')?.classList.remove('open');$('#drawerBackdrop')?.classList.remove('open');$('#settingsDrawer')?.setAttribute('aria-hidden','true');$('#settingsButton')?.setAttribute('aria-expanded','false')}
  injectAppearanceSetting();$('#settingsButton')?.addEventListener('click',open);$('#closeSettings')?.addEventListener('click',close);$('#drawerBackdrop')?.addEventListener('click',close);document.addEventListener('keydown',event=>{if(event.key==='Escape')close()});$('#headingSize')?.addEventListener('input',event=>{settings.headingSize=Number(event.target.value);apply()});$('#contentWidth')?.addEventListener('input',event=>{settings.contentWidth=Number(event.target.value);apply()});$('#densitySelect')?.addEventListener('change',event=>{settings.density=event.target.value;apply()});$('#drawerSide')?.addEventListener('change',event=>{settings.drawerSide=event.target.value;apply()});$('#customAccent')?.addEventListener('input',event=>{settings.accent=event.target.value;apply()});$$('#colorOptions button').forEach(button=>button.addEventListener('click',()=>{settings.accent=button.dataset.color;apply()}));matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(settings.appearance==='system')apply()});
  $('#saveInterface')?.addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;button.textContent='Publiceren…';try{localStorage.setItem('fitconnect-os-interface',JSON.stringify(settings));if(client){const payload={id:'default',accent:settings.accent,heading_size:Number(settings.headingSize),content_width:Number(settings.contentWidth),density:settings.density,radius:Number(settings.radius||18),updated_at:new Date().toISOString()};const {error}=await client.from('site_theme_settings').upsert(payload,{onConflict:'id'});if(error)throw error}window.fitConnectToast?.('Interface-instellingen opgeslagen');close()}catch(error){window.fitConnectToast?.(error.message||'Opslaan mislukt')}finally{button.disabled=false;button.textContent='Instellingen bewaren'}});
  $('#resetInterface')?.addEventListener('click',()=>{settings={...defaults,drawerSide:settings.drawerSide};localStorage.removeItem('fitconnect-os-interface');apply();window.fitConnectToast?.('Standaardinterface hersteld')});
  ensureCombinationDealsNavigation();addTypographyLink();apply();loadPublishedTheme();
  if(!document.querySelector('script[data-commerce-lifecycle]')){const script=document.createElement('script');script.src='commerce-lifecycle.js?v=20260815-4';script.defer=true;script.dataset.commerceLifecycle='1';document.body.appendChild(script)}
  if(!document.querySelector('script[data-customer360-operations]')){const script=document.createElement('script');script.src='customer360-operations.js?v=20260815-4';script.defer=true;script.dataset.customer360Operations='1';document.body.appendChild(script)}
  if(!document.querySelector('script[data-credit-package-manager]')){const script=document.createElement('script');script.src='credit-package-manager.js?v=20260815-1';script.defer=true;script.dataset.creditPackageManager='1';document.body.appendChild(script)}
  if(!document.querySelector('script[data-commerce-control-plane]')){const script=document.createElement('script');script.src='commerce-control-plane.js?v=20260815-4';script.defer=true;script.dataset.commerceControlPlane='1';document.body.appendChild(script)}
  if(!document.querySelector('link[data-commerce-record-context-safe]')){const link=document.createElement('link');link.rel='stylesheet';link.href='commerce-record-context-safe.css?v=20260815-1';link.dataset.commerceRecordContextSafe='1';document.head.appendChild(link)}
  if(!document.querySelector('script[data-commerce-record-context-safe]')){const script=document.createElement('script');script.src='commerce-record-context-safe.js?v=20260815-1';script.defer=true;script.dataset.commerceRecordContextSafe='1';document.body.appendChild(script)}
  if(!document.querySelector('link[data-commerce-activity-timeline-safe]')){const link=document.createElement('link');link.rel='stylesheet';link.href='commerce-activity-timeline-safe.css?v=20260816-1';link.dataset.commerceActivityTimelineSafe='1';document.head.appendChild(link)}
  if(!document.querySelector('script[data-commerce-activity-timeline-safe]')){const script=document.createElement('script');script.src='commerce-activity-timeline-safe.js?v=20260816-1';script.defer=true;script.dataset.commerceActivityTimelineSafe='1';document.body.appendChild(script)}
  if(!document.querySelector('link[data-commerce-payment-delivery-safe]')){const link=document.createElement('link');link.rel='stylesheet';link.href='commerce-payment-delivery-safe.css?v=20260816-1';link.dataset.commercePaymentDeliverySafe='1';document.head.appendChild(link)}
  if(!document.querySelector('script[data-commerce-payment-delivery-safe]')){const script=document.createElement('script');script.src='commerce-payment-delivery-safe.js?v=20260816-1';script.defer=true;script.dataset.commercePaymentDeliverySafe='1';document.body.appendChild(script)}
  if(!document.querySelector('link[data-commerce-case-intelligence-safe]')){const link=document.createElement('link');link.rel='stylesheet';link.href='commerce-case-intelligence-safe.css?v=20260816-1';link.dataset.commerceCaseIntelligenceSafe='1';document.head.appendChild(link)}
  if(!document.querySelector('script[data-commerce-case-intelligence-safe]')){const script=document.createElement('script');script.src='commerce-case-intelligence-safe.js?v=20260816-1';script.defer=true;script.dataset.commerceCaseIntelligenceSafe='1';document.body.appendChild(script)}
})();