(()=>{
  'use strict';
  class ProductServiceError extends Error{constructor({code,operation,id=null,message,cause=null,retryable=false}){super(message);this.name='ProductServiceError';this.code=code;this.operation=operation;this.id=id;this.cause=cause;this.retryable=retryable}}
  class ProductService{
    constructor(repository,config,{isOnline=()=>typeof navigator==='undefined'?true:navigator.onLine,now=()=>new Date()}={}){if(!repository)throw new TypeError('ProductRepository is verplicht.');this.repository=repository;this.config=config;this.isOnline=isOnline;this.now=now;this.pendingSaves=new Set()}
    async fetchAll(){if(!this.isOnline())throw this.normalizeError(new Error('Offline'),'fetchAll');await this.beforeLoad();try{const products=await this.repository.listProducts();await this.afterLoad(products);return products}catch(error){throw this.normalizeError(error,'fetchAll')}}
    validate(id,model){const sku=String(model.sku||'').trim(),name=String(model.name||'').trim(),price=Number(model.price),vat=Number(model.vat),status=String(model.status||'draft');if(sku&&(!this.config.skuPattern.test(sku)||sku.length>this.config.maxSkuLength))throw new ProductServiceError({code:'VALIDATION_INVALID_SKU',operation:'validate',id,message:`SKU mag maximaal ${this.config.maxSkuLength} tekens bevatten en alleen letters, cijfers, streepjes of underscores gebruiken.`});if(!name||name.length>this.config.maxProductNameLength)throw new ProductServiceError({code:'VALIDATION_INVALID_NAME',operation:'validate',id,message:`Productnaam is verplicht en mag maximaal ${this.config.maxProductNameLength} tekens bevatten.`});if(!Number.isFinite(price)||price<this.config.minPrice||price>this.config.maxPrice)throw new ProductServiceError({code:'VALIDATION_INVALID_PRICE',operation:'validate',id,message:`Verkoopprijs moet tussen ${this.config.minPrice} en ${this.config.maxPrice} liggen.`});if(!this.config.allowedVatRates.has(vat))throw new ProductServiceError({code:'VALIDATION_INVALID_VAT',operation:'validate',id,message:'Het geselecteerde btw-tarief is niet toegestaan.'});if(!this.config.allowedStatuses.has(status))throw new ProductServiceError({code:'VALIDATION_INVALID_STATUS',operation:'validate',id,message:'De geselecteerde productstatus is niet toegestaan.'})}
    async save(id,model){await this.beforeValidate(id,model);this.validate(id,model);await this.afterValidate(id,model);const key=id||'__new__';if(this.pendingSaves.has(key))throw new ProductServiceError({code:'PRODUCT_SAVE_IN_FLIGHT',operation:'save',id,message:'Dit product wordt al opgeslagen.'});if(!this.isOnline())throw this.normalizeError(new Error('Offline'),'save',id);this.pendingSaves.add(key);const prepared={...model,updatedAt:this.now().toISOString()};await this.beforeSave(id,prepared);try{const saved=await this.repository.saveProduct(id,prepared);await this.afterSave(id,saved);return saved}catch(error){throw this.normalizeError(error,'save',id)}finally{this.pendingSaves.delete(key)}}
    async beforeLoad(){} async afterLoad(){} async beforeSave(){} async afterSave(){} async beforeValidate(){} async afterValidate(){}
    normalizeError(error,operation,id=null){if(error instanceof ProductServiceError)return error;let code='PRODUCT_UNKNOWN_ERROR',message=error?.message||'Er is een productfout opgetreden.',retryable=true;if(error?.message==='Offline'||!this.isOnline()){code='NETWORK_OFFLINE';message='Geen internetverbinding beschikbaar.'}else if(error?.code==='42501'){code='PRODUCT_SAVE_FORBIDDEN';message='U heeft onvoldoende rechten om producten te beheren.';retryable=false}return new ProductServiceError({code,operation,id,message,cause:error,retryable})}
  }
  window.ProductServiceError=ProductServiceError;window.ProductService=ProductService;
})();
