(()=>{'use strict';
const client=window.getFitConnectSupabase?.(),list=document.getElementById('ordersList'),detail=document.getElementById('orderDetail'),statusEl=document.getElementById('ordersStatus');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const euro=v=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
const date=v=>new Intl.DateTimeFormat('nl-NL',{dateStyle:'long'}).format(new Date(v));
const labels={processing:'Wordt verwerkt',confirmed:'Bevestigd',picking:'Wordt verzameld',packed:'Klaar voor verzending',shipped:'Verzonden',delivered:'Bezorgd',cancelled:'Geannuleerd',returned:'Retour',created:'Aangemaakt',pending:'In behandeling',paid:'Betaald',failed:'Mislukt',expired:'Verlopen',refunded:'Terugbetaald',partially_refunded:'Deels terugbetaald'};
function setStatus(text,error=false){statusEl.textContent=text;statusEl.classList.toggle('error',error)}
function reference(order){return `FC-${order.id.slice(0,8).toUpperCase()}`}
function paymentOf(order){const payments=Array.isArray(order.commerce_payments)?order.commerce_payments:[];return payments.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]||{status:'pending'}}
function progress(status){const steps=['processing','confirmed','packed','shipped','delivered'],i=Math.max(0,steps.indexOf(status));return steps.map((step,index)=>`<li class="${index<=i?'done':''}"><i>${index<i?'✓':index+1}</i><span>${labels[step]}</span></li>`).join('')}
function renderList(orders){detail.hidden=true;list.hidden=false;if(!orders.length){list.innerHTML='<article class="empty"><h2>Nog geen bestellingen</h2><p>Na uw eerste aankoop verschijnt de volledige voortgang hier automatisch.</p><a href="../../shop/">Naar de shop</a></article>';return}list.innerHTML=orders.map(order=>{const payment=paymentOf(order);return `<article class="order-card"><div><small>${esc(reference(order))} · ${esc(date(order.created_at))}</small><h2>${esc(labels[order.order_status]||'Wordt verwerkt')}</h2><p>${order.commerce_cart_items?.length||0} artikel(en) · ${esc(euro(order.grand_total))}</p></div><div class="order-actions"><span class="pill ${payment.status==='paid'?'paid':''}">${esc(labels[payment.status]||payment.status)}</span><button type="button" data-order="${order.id}">Bekijk bestelling</button></div></article>`}).join('');list.querySelectorAll('[data-order]').forEach(button=>button.addEventListener('click',()=>showDetail(orders.find(order=>order.id===button.dataset.order))))}
function showDetail(order){if(!order)return;const payment=paymentOf(order),address=order.shipping_address||{},tracking=order.tracking_code?`<a class="tracking" href="${esc(order.tracking_url||'#')}" ${order.tracking_url?'target="_blank" rel="noopener"':''}><strong>${esc(order.tracking_carrier||'Vervoerder')}</strong><span>${esc(order.tracking_code)}</span></a>`:'<p class="muted">Track & Trace verschijnt hier zodra uw bestelling is verzonden.</p>';list.hidden=true;detail.hidden=false;detail.innerHTML=`<button class="back" type="button">← Alle bestellingen</button><div class="detail-head"><div><p class="eyebrow">${esc(reference(order))}</p><h2>${esc(labels[order.order_status]||'Wordt verwerkt')}</h2><p>Besteld op ${esc(date(order.created_at))}</p></div><span class="pill ${payment.status==='paid'?'paid':''}">${esc(labels[payment.status]||payment.status)}</span></div><ol class="journey">${progress(order.order_status)}</ol><div class="detail-grid"><section><h3>Artikelen</h3>${(order.commerce_cart_items||[]).map(item=>`<div class="line"><span>${esc(item.product_name)} × ${Number(item.quantity)}</span><strong>${esc(euro(Number(item.unit_price)*(1+Number(item.tax_rate)/100)*Number(item.quantity)))}</strong></div>`).join('')}<div class="line total"><span>Totaal incl. btw</span><strong>${esc(euro(order.grand_total))}</strong></div></section><section><h3>Bezorgadres</h3><p>${esc(`${order.first_name} ${order.last_name}`)}<br>${esc(`${address.street||''} ${address.house_number||''}`)}<br>${esc(`${address.postal_code||''} ${address.city||''}`)}</p><h3>Track & Trace</h3>${tracking}</section></div>`;detail.querySelector('.back').addEventListener('click',()=>renderList(window.__fitconnectOrders||[]))}
async function load(){if(!client){location.replace('../../login/?login=required');return}const {data:{session}}=await client.auth.getSession();if(!session){location.replace('../../login/?login=required');return}const {data:profile,error:profileError}=await client.from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(profileError||!profile){location.replace('../../login/?denied=1');return}const {data,error}=await client.from('commerce_checkout_sessions').select('id,created_at,first_name,last_name,shipping_address,grand_total,currency,order_status,tracking_carrier,tracking_code,tracking_url,commerce_payments(status,created_at),commerce_cart_items:commerce_carts!inner(commerce_cart_items(product_name,quantity,unit_price,tax_rate))').eq('user_id',session.user.id).order('created_at',{ascending:false});if(error)throw error;const orders=(data||[]).map(order=>({...order,commerce_cart_items:order.commerce_cart_items?.commerce_cart_items||[]}));window.__fitconnectOrders=orders;setStatus(`${orders.length} bestelling${orders.length===1?'':'en'}`);const selected=new URLSearchParams(location.search).get('order');selected?showDetail(orders.find(order=>order.id===selected)):renderList(orders)}
document.getElementById('logoutButton').addEventListener('click',async()=>{if(client)await client.auth.signOut({scope:'local'});location.replace('../../login/?logout=1')});
load().catch(error=>{console.error(error);setStatus('Uw bestellingen konden niet worden geladen.',true)});
})();
