-- My Twin image hardening v1
-- Heavy source files (up to 50 MB) are normalized client-side and are never persisted.
-- Only server-validated processed assets are written to the private avatars bucket.

alter table public.user_avatars
  add column if not exists source_sha256 text,
  add column if not exists source_bytes integer check (source_bytes is null or source_bytes >= 0),
  add column if not exists processed_bytes integer check (processed_bytes is null or processed_bytes >= 0),
  add column if not exists processed_width integer check (processed_width is null or processed_width > 0),
  add column if not exists processed_height integer check (processed_height is null or processed_height > 0);

alter table public.avatar_versions
  add column if not exists source_sha256 text,
  add column if not exists source_bytes integer check (source_bytes is null or source_bytes >= 0),
  add column if not exists processed_bytes integer check (processed_bytes is null or processed_bytes >= 0),
  add column if not exists processed_width integer check (processed_width is null or processed_width > 0),
  add column if not exists processed_height integer check (processed_height is null or processed_height > 0);

create table if not exists public.avatar_ingest_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  attempted_at timestamptz not null default now()
);

create index if not exists avatar_ingest_attempts_user_time_idx
  on public.avatar_ingest_attempts (user_id, attempted_at desc);

alter table public.avatar_ingest_attempts enable row level security;
revoke all on public.avatar_ingest_attempts from anon, authenticated;
revoke all on sequence public.avatar_ingest_attempts_id_seq from anon, authenticated;

-- Processed assets remain private and intentionally small. The 50 MB source limit is a
-- client intake limit, not a Storage limit: originals never enter the backend.
update storage.buckets
set public = false,
    file_size_limit = 5242880,
    allowed_mime_types = array['image/webp','image/jpeg']
where id = 'avatars';

-- Direct writes from browsers are removed. Only the authenticated Edge Function writes
-- through the service role after validation and metadata stripping.
drop policy if exists "Users can upload own avatar files" on storage.objects;
drop policy if exists "Users can update own avatar files" on storage.objects;
drop policy if exists "Users can delete own avatar files" on storage.objects;

-- Keep private read access scoped to the authenticated owner's folder.
drop policy if exists "Users can view own avatar files" on storage.objects;
create policy "Users can view own avatar files"
on storage.objects for select to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);
