import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"https://fitconnect.nl","Access-Control-Allow-Headers":"authorization,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json"}});
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{
 const auth=req.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return json({error:'Authentication required'},401);
 const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,mollie=Deno.env.get('MOLLIE_API_KEY')!,org=Deno.env.get('FITCONNECT_ORGANIZATION_ID')!,returnUrl=Deno.env.get('CREDIT_RETURN_URL')||'https://fitconnect.nl/portal/customer360/';
 const sb=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error:uerr}=await sb.auth.getUser(token);if(uerr||!user)return json({error:'Authentication required'},401);
 const body=await req.json();const packageId=String(body.packageId||'');const idempotencyKey=String(body.idempotencyKey||'');if(!uuid.test(packageId)||!uuid.test(idempotencyKey))return json({error:'Ongeldige aanvraag'},400);
 const {data:existing,error:ee}=await sb.from('customer_credit_purchases').select('id,status,checkout_url').eq('organization_id',org).eq('customer_user_id',user.id).eq('idempotency_key',idempotencyKey).maybeSingle();if(ee)throw ee;if(existing?.checkout_url&&['created','pending'].includes(existing.status))return json({purchaseId:existing.id,checkoutUrl:existing.checkout_url});
 const {data:p,error:pe}=await sb.from('customer_credit_packages').select('id,name,price,credit_amount,currency').eq('id',packageId).eq('organization_id',org).eq('active',true).single();if(pe||!p)return json({error:'Creditpakket niet beschikbaar'},404);
 const {data:purchase,error:ie}=await sb.from('customer_credit_purchases').insert({organization_id:org,customer_user_id:user.id,package_id:p.id,amount_paid:p.price,credit_amount:p.credit_amount,currency:p.currency,provider:'mollie',status:'created',idempotency_key:idempotencyKey}).select('id').single();if(ie)throw ie;
 const webhookUrl=`${url}/functions/v1/customer-credit-mollie-webhook`;const mr=await fetch('https://api.mollie.com/v2/payments',{method:'POST',headers:{authorization:`Bearer ${mollie}`,'content-type':'application/json','Idempotency-Key':`credit-${purchase.id}`},body:JSON.stringify({amount:{currency:p.currency,value:Number(p.price).toFixed(2)},description:`${p.name} · FitConnect tegoed`,redirectUrl:returnUrl,webhookUrl,metadata:{type:'credit_purchase',purchaseId:purchase.id,organizationId:org,customerUserId:user.id}})});const payment=await mr.json();if(!mr.ok){await sb.from('customer_credit_purchases').update({status:'failed',updated_at:new Date().toISOString()}).eq('id',purchase.id);return json({error:'Betaling kon niet worden aangemaakt'},502)}
 const checkoutUrl=payment?._links?.checkout?.href;if(!payment.id||!checkoutUrl)throw new Error('Invalid Mollie response');await sb.from('customer_credit_purchases').update({provider_payment_id:payment.id,checkout_url:checkoutUrl,status:'pending',updated_at:new Date().toISOString()}).eq('id',purchase.id);return json({purchaseId:purchase.id,checkoutUrl});
 }catch(e){console.error(e);return json({error:'Creditbetaling kon niet worden gestart'},500)}});
