(()=>{'use strict';
const client=window.getFitConnectSupabase?.();
const root=document.getElementById('wallet');if(!client||!root)return;
const balanceEl=document.getElementById('walletBalance'),packageList=document.getElementById('creditPackageList'),history=document.getElementById('creditHistory'),ledgerRoot=document.getElementById('walletLedger'),returnEl=document.getElementById('creditReturn');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(v,c='EUR')=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:String(c||'EUR').toUpperCase()}).format(Number(v||0));
const credits=v=>`${new Intl.NumberFormat('nl-NL',{maximumFractionDigits:2}).format(Number(v||0))} credits`;
const date=v=>v?new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
const state=v=>({created:'Aangemaakt',pending:'Wacht op betaling',paid:'Betaald',failed:'Mislukt',cancelled:'Geannuleerd',expired:'Verlopen',refunded:'Terugbetaald'})[v]||v;
const entryLabel=v=>({purchase:'Aankoop',subscription_credit:'Abonnement',manual_credit:'Handmatig tegoed',redemption:'Gebruikt',refund:'Terugboeking',expiry:'Verlopen',correction:'Correctie'})[v]||v;
let session=null,packages=[],purchases=[],ledger=[];
async function load(){const s=await client.auth.getSession();session=s.data.session;if(!session)return;const[{data:balances,error:be},{data:packageRows,error:pe},{data:purchaseRows,error:he},{data:ledgerRows,error:le}]=await Promise.all([client.from('customer_wallet_balances').select('balance,currency'),client.from('customer_credit_packages').select('id,name,description,price,credit_amount,currency').eq('active',true).order('sort_order').order('price'),client.from('customer_credit_purchases').select('id,package_id,amount_paid,credit_amount,currency,status,paid_at,credited_at,created_at,checkout_url').order('created_at',{ascending:false}).limit(30),client.from('customer_wallet_ledger').select('id,entry_type,amount,currency,description,reference_type,reference_id,created_at').order('created_at',{ascending:false}).limit(50)]);if(be)throw be;if(pe)throw pe;if(he)throw he;if(le)throw le;packages=packageRows||[];purchases=purchaseRows||[];ledger=ledgerRows||[];const balance=(balances||[]).reduce((n,x)=>n+Number(x.balance||0),0);balanceEl.textContent=credits(balance);renderPackages();renderHistory();renderLedger()}
function renderPackages(){packageList.innerHTML=packages.length?packages.map(p=>`<article class="wallet-package"><div><h4>${esc(p.name)}</h4><p>${esc(p.description||'Direct beschikbaar na succesvolle betaling.')}</p></div><div class="wallet-package-value"><strong>${esc(credits(p.credit_amount))}</strong><span>${esc(money(p.price,p.currency))}</span></div><button class="primary" type="button" data-buy-credit="${p.id}">Kopen</button></article>`).join(''):'<p>Er zijn momenteel geen actieve creditpakketten.</p>'}
function renderHistory(){history.innerHTML=purchases.length?purchases.map(p=>`<article class="wallet-history-row"><div><strong>${esc(credits(p.credit_amount))}</strong><span>${esc(date(p.created_at))}</span></div><div><span class="wallet-state" data-state="${esc(p.status)}">${esc(state(p.status))}</span><strong>${esc(money(p.amount_paid,p.currency))}</strong></div></article>`).join(''):'<p>Nog geen tegoedaankopen.</p>'}
function renderLedger(){if(!ledgerRoot)return;ledgerRoot.innerHTML=ledger.length?ledger.map(x=>{const amount=Number(x.amount||0),sign=amount>0?'+':'';return `<article class="wallet-history-row"><div><strong>${esc(x.description||entryLabel(x.entry_type))}</strong><span>${esc(entryLabel(x.entry_type))} · ${esc(date(x.created_at))}</span></div><div><span class="wallet-state" data-state="${amount<0?'debit':'credit'}">${amount<0?'Af':'Bij'}</span><strong>${esc(`${sign}${credits(amount)}`)}</strong></div></article>`}).join(''):'<p>Nog geen wallettransacties.</p>'}
async function buy(packageId,button){button.disabled=true;const old=button.textContent;button.textContent='Betaling starten…';try{const key=crypto.randomUUID();const {data,error}=await client.functions.invoke('customer-create-credit-payment',{body:{packageId,idempotencyKey:key}});if(error)throw error;if(!data?.checkoutUrl)throw new Error(data?.error||'Geen betaallink ontvangen');location.href=data.checkoutUrl}catch(e){returnEl.hidden=false;returnEl.className='credit-return error';returnEl.textContent=e?.message||'Creditbetaling kon niet worden gestart';button.disabled=false;button.textContent=old}}
async function checkReturn(){const params=new URLSearchParams(location.search);if(params.get('credit')!=='return')return;returnEl.hidden=false;returnEl.className='credit-return';returnEl.textContent='Betaling wordt gecontroleerd…';let tries=0;const poll=async()=>{tries++;try{await load();const latest=purchases[0];if(latest?.status==='paid'&&latest?.credited_at){returnEl.className='credit-return success';returnEl.textContent=`Betaling verwerkt. ${credits(latest.credit_amount)} zijn toegevoegd aan uw tegoed.`;ledgerRoot?.scrollIntoView({behavior:'smooth',block:'nearest'});return}if(latest&&['failed','cancelled','expired'].includes(latest.status)){returnEl.className='credit-return error';returnEl.textContent=`Betaling ${state(latest.status).toLowerCase()}. Uw tegoed is niet gewijzigd.`;return}}catch{}if(tries<12)setTimeout(poll,1250);else{returnEl.textContent='De betaling wordt nog verwerkt. Vernieuw deze pagina over enkele seconden.'}};poll()}
root.addEventListener('click',e=>{const b=e.target.closest('[data-buy-credit]');if(b)buy(b.dataset.buyCredit,b)});
(async()=>{try{await load();await checkReturn()}catch(e){packageList.innerHTML='<p>Wallet kon niet worden geladen.</p>';console.warn('wallet',e)}})();
})();